import SwiftUI

enum ChemistryData {

    // MARK: - ВСЕ 118 ЭЛЕМЕНТОВ + СОЕДИНЕНИЯ + ОРГАНИКА
    static let reagents: [Reagent] = [
        // ========== 1 ПЕРИОД ==========
        Reagent(symbol: "H",   name: "Водород",         colorHex: "#FF6B6B", group: .elements),
        Reagent(symbol: "He",  name: "Гелий",           colorHex: "#FCA5A5", group: .elements),

        // ========== 2 ПЕРИОД ==========
        Reagent(symbol: "Li",  name: "Литий",           colorHex: "#F472B6", group: .elements),
        Reagent(symbol: "Be",  name: "Бериллий",        colorHex: "#FB7185", group: .elements),
        Reagent(symbol: "B",   name: "Бор",             colorHex: "#F59E0B", group: .elements),
        Reagent(symbol: "C",   name: "Углерод",         colorHex: "#4B5563", group: .elements),
        Reagent(symbol: "N",   name: "Азот",            colorHex: "#3B82F6", group: .elements),
        Reagent(symbol: "O",   name: "Кислород",        colorHex: "#EF4444", group: .elements),
        Reagent(symbol: "F",   name: "Фтор",            colorHex: "#22C55E", group: .elements),
        Reagent(symbol: "Ne",  name: "Неон",            colorHex: "#F87171", group: .elements),

        // ========== 3 ПЕРИОД ==========
        Reagent(symbol: "Na",  name: "Натрий",          colorHex: "#F97316", group: .elements),
        Reagent(symbol: "Mg",  name: "Магний",          colorHex: "#FACC15", group: .elements),
        Reagent(symbol: "Al",  name: "Алюминий",        colorHex: "#9CA3AF", group: .elements),
        Reagent(symbol: "Si",  name: "Кремний",         colorHex: "#78716C", group: .elements),
        Reagent(symbol: "P",   name: "Фосфор",          colorHex: "#F97316", group: .elements),
        Reagent(symbol: "S",   name: "Сера",            colorHex: "#FACC15", group: .elements),
        Reagent(symbol: "Cl",  name: "Хлор",            colorHex: "#4ADE80", group: .elements),
        Reagent(symbol: "Ar",  name: "Аргон",           colorHex: "#A78BFA", group: .elements),

        // ========== 4 ПЕРИОД ==========
        Reagent(symbol: "K",   name: "Калий",           colorHex: "#EA580C", group: .elements),
        Reagent(symbol: "Ca",  name: "Кальций",         colorHex: "#FCD34D", group: .elements),
        Reagent(symbol: "Sc",  name: "Скандий",         colorHex: "#A1A1AA", group: .elements),
        Reagent(symbol: "Ti",  name: "Титан",           colorHex: "#94A3B8", group: .elements),
        Reagent(symbol: "V",   name: "Ванадий",         colorHex: "#71717A", group: .elements),
        Reagent(symbol: "Cr",  name: "Хром",            colorHex: "#0891B2", group: .elements),
        Reagent(symbol: "Mn",  name: "Марганец",        colorHex: "#7E22CE", group: .elements),
        Reagent(symbol: "Fe",  name: "Железо",          colorHex: "#B45309", group: .elements),
        Reagent(symbol: "Co",  name: "Кобальт",         colorHex: "#1D4ED8", group: .elements),
        Reagent(symbol: "Ni",  name: "Никель",          colorHex: "#65A30D", group: .elements),
        Reagent(symbol: "Cu",  name: "Медь",            colorHex: "#EA580C", group: .elements),
        Reagent(symbol: "Zn",  name: "Цинк",            colorHex: "#94A3B8", group: .elements),
        Reagent(symbol: "Ga",  name: "Галлий",          colorHex: "#64748B", group: .elements),
        Reagent(symbol: "Ge",  name: "Германий",        colorHex: "#525252", group: .elements),
        Reagent(symbol: "As",  name: "Арсен",           colorHex: "#7C3AED", group: .elements),
        Reagent(symbol: "Se",  name: "Селен",           colorHex: "#CA8A04", group: .elements),
        Reagent(symbol: "Br",  name: "Бром",            colorHex: "#B91C1C", group: .elements),
        Reagent(symbol: "Kr",  name: "Криптон",         colorHex: "#0EA5E9", group: .elements),

        // ========== 5 ПЕРИОД ==========
        Reagent(symbol: "Rb",  name: "Рубидий",         colorHex: "#DC2626", group: .elements),
        Reagent(symbol: "Sr",  name: "Стронций",        colorHex: "#FCD34D", group: .elements),
        Reagent(symbol: "Y",   name: "Иттрий",          colorHex: "#A3A3A3", group: .elements),
        Reagent(symbol: "Zr",  name: "Цирконий",        colorHex: "#737373", group: .elements),
        Reagent(symbol: "Nb",  name: "Ниобий",          colorHex: "#404040", group: .elements),
        Reagent(symbol: "Mo",  name: "Молибден",        colorHex: "#525252", group: .elements),
        Reagent(symbol: "Tc",  name: "Технеций",        colorHex: "#7E22CE", group: .elements),
        Reagent(symbol: "Ru",  name: "Рутений",         colorHex: "#334155", group: .elements),
        Reagent(symbol: "Rh",  name: "Родий",           colorHex: "#94A3B8", group: .elements),
        Reagent(symbol: "Pd",  name: "Палладий",        colorHex: "#CBD5E1", group: .elements),
        Reagent(symbol: "Ag",  name: "Серебро",         colorHex: "#CBD5E1", group: .elements),
        Reagent(symbol: "Cd",  name: "Кадмий",          colorHex: "#71717A", group: .elements),
        Reagent(symbol: "In",  name: "Индий",           colorHex: "#A1A1AA", group: .elements),
        Reagent(symbol: "Sn",  name: "Олово",           colorHex: "#D4D4D8", group: .elements),
        Reagent(symbol: "Sb",  name: "Сурьма",          colorHex: "#525252", group: .elements),
        Reagent(symbol: "Te",  name: "Теллур",          colorHex: "#A16207", group: .elements),
        Reagent(symbol: "I",   name: "Иод",             colorHex: "#7C3AED", group: .elements),
        Reagent(symbol: "Xe",  name: "Ксенон",          colorHex: "#06B6D4", group: .elements),

        // ========== 6 ПЕРИОД ==========
        Reagent(symbol: "Cs",  name: "Цезий",           colorHex: "#F59E0B", group: .elements),
        Reagent(symbol: "Ba",  name: "Барий",           colorHex: "#22D3EE", group: .elements),
        Reagent(symbol: "La",  name: "Лантан",          colorHex: "#94A3B8", group: .elements),
        Reagent(symbol: "Ce",  name: "Церий",           colorHex: "#A1A1AA", group: .elements),
        Reagent(symbol: "Pr",  name: "Празеодим",       colorHex: "#71717A", group: .elements),
        Reagent(symbol: "Nd",  name: "Неодим",          colorHex: "#A3A3A3", group: .elements),
        Reagent(symbol: "Pm",  name: "Прометий",        colorHex: "#84CC16", group: .elements),
        Reagent(symbol: "Sm",  name: "Самарий",         colorHex: "#65A30D", group: .elements),
        Reagent(symbol: "Eu",  name: "Европий",         colorHex: "#A3E635", group: .elements),
        Reagent(symbol: "Gd",  name: "Гадолиний",       colorHex: "#737373", group: .elements),
        Reagent(symbol: "Tb",  name: "Тербий",          colorHex: "#525252", group: .elements),
        Reagent(symbol: "Dy",  name: "Диспрозий",       colorHex: "#404040", group: .elements),
        Reagent(symbol: "Ho",  name: "Гольмий",         colorHex: "#A16207", group: .elements),
        Reagent(symbol: "Er",  name: "Эрбий",           colorHex: "#7E22CE", group: .elements),
        Reagent(symbol: "Tm",  name: "Тулий",           colorHex: "#0369A1", group: .elements),
        Reagent(symbol: "Yb",  name: "Иттербий",        colorHex: "#0EA5E9", group: .elements),
        Reagent(symbol: "Lu",  name: "Лютеций",         colorHex: "#22D3EE", group: .elements),
        Reagent(symbol: "Hf",  name: "Гафний",          colorHex: "#64748B", group: .elements),
        Reagent(symbol: "Ta",  name: "Тантал",          colorHex: "#525252", group: .elements),
        Reagent(symbol: "W",   name: "Вольфрам",        colorHex: "#404040", group: .elements),
        Reagent(symbol: "Re",  name: "Рений",           colorHex: "#57534E", group: .elements),
        Reagent(symbol: "Os",  name: "Осмий",           colorHex: "#1C1917", group: .elements),
        Reagent(symbol: "Ir",  name: "Иридий",          colorHex: "#CBD5E1", group: .elements),
        Reagent(symbol: "Pt",  name: "Платина",         colorHex: "#E2E8F0", group: .elements),
        Reagent(symbol: "Au",  name: "Золото",          colorHex: "#FBBF24", group: .elements),
        Reagent(symbol: "Hg",  name: "Ртуть",           colorHex: "#A1A1AA", group: .elements),
        Reagent(symbol: "Tl",  name: "Таллий",          colorHex: "#71717A", group: .elements),
        Reagent(symbol: "Pb",  name: "Свинец",          colorHex: "#64748B", group: .elements),
        Reagent(symbol: "Bi",  name: "Висмут",          colorHex: "#A78BFA", group: .elements),
        Reagent(symbol: "Po",  name: "Полоний",         colorHex: "#7E22CE", group: .elements),
        Reagent(symbol: "At",  name: "Астат",           colorHex: "#84CC16", group: .elements),
        Reagent(symbol: "Rn",  name: "Радон",           colorHex: "#0EA5E9", group: .elements),

        // ========== 7 ПЕРИОД ==========
        Reagent(symbol: "Fr",  name: "Франций",         colorHex: "#DC2626", group: .elements),
        Reagent(symbol: "Ra",  name: "Радий",           colorHex: "#22D3EE", group: .elements),
        Reagent(symbol: "Ac",  name: "Актиний",         colorHex: "#84CC16", group: .elements),
        Reagent(symbol: "Th",  name: "Торий",           colorHex: "#737373", group: .elements),
        Reagent(symbol: "Pa",  name: "Протактиний",     colorHex: "#525252", group: .elements),
        Reagent(symbol: "U",   name: "Уран",            colorHex: "#22C55E", group: .elements),
        Reagent(symbol: "Np",  name: "Нептуний",        colorHex: "#0EA5E9", group: .elements),
        Reagent(symbol: "Pu",  name: "Плутоний",        colorHex: "#DC2626", group: .elements),
        Reagent(symbol: "Am",  name: "Америций",        colorHex: "#F59E0B", group: .elements),
        Reagent(symbol: "Cm",  name: "Кюрий",           colorHex: "#A855F7", group: .elements),
        Reagent(symbol: "Bk",  name: "Берклий",         colorHex: "#84CC16", group: .elements),
        Reagent(symbol: "Cf",  name: "Калифорний",      colorHex: "#F97316", group: .elements),
        Reagent(symbol: "Es",  name: "Эйнштейний",      colorHex: "#EF4444", group: .elements),
        Reagent(symbol: "Fm",  name: "Фермий",          colorHex: "#0EA5E9", group: .elements),
        Reagent(symbol: "Md",  name: "Менделевий",      colorHex: "#A855F7", group: .elements),
        Reagent(symbol: "No",  name: "Нобелий",         colorHex: "#F59E0B", group: .elements),
        Reagent(symbol: "Lr",  name: "Лоуренсий",       colorHex: "#22C55E", group: .elements),
        Reagent(symbol: "Rf",  name: "Резерфордий",     colorHex: "#EF4444", group: .elements),
        Reagent(symbol: "Db",  name: "Дубний",          colorHex: "#F97316", group: .elements),
        Reagent(symbol: "Sg",  name: "Сиборгий",        colorHex: "#8B5CF6", group: .elements),
        Reagent(symbol: "Bh",  name: "Борий",           colorHex: "#06B6D4", group: .elements),
        Reagent(symbol: "Hs",  name: "Хассий",          colorHex: "#10B981", group: .elements),
        Reagent(symbol: "Mt",  name: "Мейтнерий",       colorHex: "#EC4899", group: .elements),
        Reagent(symbol: "Ds",  name: "Дармштадтий",     colorHex: "#A855F7", group: .elements),
        Reagent(symbol: "Rg",  name: "Рентгений",       colorHex: "#F59E0B", group: .elements),
        Reagent(symbol: "Cn",  name: "Коперниций",      colorHex: "#84CC16", group: .elements),
        Reagent(symbol: "Nh",  name: "Нихоний",         colorHex: "#0EA5E9", group: .elements),
        Reagent(symbol: "Fl",  name: "Флеровий",        colorHex: "#EF4444", group: .elements),
        Reagent(symbol: "Mc",  name: "Московий",        colorHex: "#F97316", group: .elements),
        Reagent(symbol: "Lv",  name: "Ливерморий",      colorHex: "#A855F7", group: .elements),
        Reagent(symbol: "Ts",  name: "Теннессин",       colorHex: "#06B6D4", group: .elements),
        Reagent(symbol: "Og",  name: "Оганесон",        colorHex: "#10B981", group: .elements),

        // ============ ОКСИДЫ ============
        Reagent(symbol: "H2O",     name: "Вода",               colorHex: "#60A5FA", group: .compounds),
        Reagent(symbol: "Li2O",    name: "Оксид лития",        colorHex: "#FBCFE8", group: .compounds),
        Reagent(symbol: "Na2O",    name: "Оксид натрия",       colorHex: "#FDBA74", group: .compounds),
        Reagent(symbol: "K2O",     name: "Оксид калия",        colorHex: "#FDBA74", group: .compounds),
        Reagent(symbol: "CaO",     name: "Оксид кальция",      colorHex: "#FDE68A", group: .compounds),
        Reagent(symbol: "MgO",     name: "Оксид магния",       colorHex: "#FEF08A", group: .compounds),
        Reagent(symbol: "BaO",     name: "Оксид бария",        colorHex: "#FCD34D", group: .compounds),
        Reagent(symbol: "Al2O3",   name: "Оксид алюминия",     colorHex: "#D4D4D8", group: .compounds),
        Reagent(symbol: "Fe2O3",   name: "Оксид железа(III)",  colorHex: "#92400E", group: .compounds),
        Reagent(symbol: "FeO",     name: "Оксид железа(II)",   colorHex: "#1C1917", group: .compounds),
        Reagent(symbol: "CuO",     name: "Оксид меди(II)",     colorHex: "#1F2937", group: .compounds),
        Reagent(symbol: "Cu2O",    name: "Оксид меди(I)",      colorHex: "#991B1B", group: .compounds),
        Reagent(symbol: "ZnO",     name: "Оксид цинка",        colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "PbO",     name: "Оксид свинца(II)",   colorHex: "#FCD34D", group: .compounds),
        Reagent(symbol: "MnO2",    name: "Оксид марганца(IV)", colorHex: "#1F2937", group: .compounds),
        Reagent(symbol: "Cr2O3",   name: "Оксид хрома(III)",   colorHex: "#065F46", group: .compounds),
        Reagent(symbol: "B2O3",    name: "Оксид бора",         colorHex: "#FEF08A", group: .compounds),
        Reagent(symbol: "SiO2",    name: "Оксид кремния",      colorHex: "#A8A29E", group: .compounds),
        Reagent(symbol: "TiO2",    name: "Оксид титана(IV)",   colorHex: "#E2E8F0", group: .compounds),
        Reagent(symbol: "SnO2",    name: "Оксид олова(IV)",    colorHex: "#D4D4D8", group: .compounds),
        Reagent(symbol: "CO",      name: "Оксид углерода(II)", colorHex: "#71717A", group: .compounds),
        Reagent(symbol: "CO2",     name: "Оксид углерода(IV)", colorHex: "#94A3B8", group: .compounds),
        Reagent(symbol: "NO",      name: "Оксид азота(II)",    colorHex: "#3B82F6", group: .compounds),
        Reagent(symbol: "NO2",     name: "Оксид азота(IV)",    colorHex: "#92400E", group: .compounds),
        Reagent(symbol: "N2O5",    name: "Оксид азота(V)",     colorHex: "#DBEAFE", group: .compounds),
        Reagent(symbol: "SO2",     name: "Оксид серы(IV)",     colorHex: "#CBD5E1", group: .compounds),
        Reagent(symbol: "SO3",     name: "Оксид серы(VI)",     colorHex: "#CBD5E1", group: .compounds),
        Reagent(symbol: "P2O5",    name: "Оксид фосфора(V)",   colorHex: "#FB923C", group: .compounds),

        // ============ ОСНОВАНИЯ ============
        Reagent(symbol: "LiOH",    name: "Гидроксид лития",    colorHex: "#F9A8D4", group: .compounds),
        Reagent(symbol: "NaOH",    name: "Гидроксид натрия",   colorHex: "#A78BFA", group: .compounds),
        Reagent(symbol: "KOH",     name: "Гидроксид калия",    colorHex: "#C084FC", group: .compounds),
        Reagent(symbol: "Ca(OH)2", name: "Гидроксид кальция",  colorHex: "#E9D5FF", group: .compounds),
        Reagent(symbol: "Ba(OH)2", name: "Гидроксид бария",    colorHex: "#DDD6FE", group: .compounds),
        Reagent(symbol: "NH4OH",   name: "Гидроксид аммония",  colorHex: "#C7D2FE", group: .compounds),
        Reagent(symbol: "Cu(OH)2", name: "Гидроксид меди(II)", colorHex: "#2563EB", group: .compounds),
        Reagent(symbol: "Fe(OH)3", name: "Гидроксид железа(III)",colorHex: "#7C2D12", group: .compounds),
        Reagent(symbol: "Fe(OH)2", name: "Гидроксид железа(II)",colorHex: "#365314", group: .compounds),
        Reagent(symbol: "Al(OH)3", name: "Гидроксид алюминия", colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "Mg(OH)2", name: "Гидроксид магния",   colorHex: "#FEF3C7", group: .compounds),
        Reagent(symbol: "Zn(OH)2", name: "Гидроксид цинка",    colorHex: "#E5E7EB", group: .compounds),

        // ============ КИСЛОТЫ ============
        Reagent(symbol: "HCl",     name: "Соляная кислота",    colorHex: "#FCD34D", group: .compounds),
        Reagent(symbol: "H2SO4",   name: "Серная кислота",     colorHex: "#FBBF24", group: .compounds),
        Reagent(symbol: "HNO3",    name: "Азотная кислота",    colorHex: "#F59E0B", group: .compounds),
        Reagent(symbol: "H3PO4",   name: "Фосфорная кислота",  colorHex: "#F97316", group: .compounds),
        Reagent(symbol: "HF",      name: "Фтороводород",       colorHex: "#22C55E", group: .compounds),
        Reagent(symbol: "HBr",     name: "Бромоводород",       colorHex: "#B91C1C", group: .compounds),
        Reagent(symbol: "HI",      name: "Иодоводород",        colorHex: "#7C3AED", group: .compounds),
        Reagent(symbol: "H2S",     name: "Сероводород",        colorHex: "#FACC15", group: .compounds),
        Reagent(symbol: "H2CO3",   name: "Угольная кислота",   colorHex: "#94A3B8", group: .compounds),
        Reagent(symbol: "H2SiO3",  name: "Кремниевая кислота", colorHex: "#A8A29E", group: .compounds),
        Reagent(symbol: "H3BO3",   name: "Борная кислота",     colorHex: "#FEF08A", group: .compounds),

        // ============ СОЛИ ============
        Reagent(symbol: "NaCl",    name: "Хлорид натрия",      colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "KCl",     name: "Хлорид калия",       colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "LiCl",    name: "Хлорид лития",       colorHex: "#FBCFE8", group: .compounds),
        Reagent(symbol: "CaCl2",   name: "Хлорид кальция",     colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "BaCl2",   name: "Хлорид бария",       colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "CuCl2",   name: "Хлорид меди(II)",    colorHex: "#0891B2", group: .compounds),
        Reagent(symbol: "FeCl3",   name: "Хлорид железа(III)", colorHex: "#B45309", group: .compounds),
        Reagent(symbol: "FeCl2",   name: "Хлорид железа(II)",  colorHex: "#365314", group: .compounds),
        Reagent(symbol: "ZnCl2",   name: "Хлорид цинка",       colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "AlCl3",   name: "Хлорид алюминия",    colorHex: "#D4D4D8", group: .compounds),
        Reagent(symbol: "MgCl2",   name: "Хлорид магния",      colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "AgCl",    name: "Хлорид серебра",     colorHex: "#F8FAFC", group: .compounds),
        Reagent(symbol: "NiCl2",   name: "Хлорид никеля(II)",  colorHex: "#65A30D", group: .compounds),
        Reagent(symbol: "CoCl2",   name: "Хлорид кобальта(II)",colorHex: "#1D4ED8", group: .compounds),
        Reagent(symbol: "CrCl3",   name: "Хлорид хрома(III)",  colorHex: "#065F46", group: .compounds),
        Reagent(symbol: "NaBr",    name: "Бромид натрия",      colorHex: "#FEE2E2", group: .compounds),
        Reagent(symbol: "KBr",     name: "Бромид калия",       colorHex: "#FEE2E2", group: .compounds),
        Reagent(symbol: "AgBr",    name: "Бромид серебра",     colorHex: "#FEF3C7", group: .compounds),
        Reagent(symbol: "NaI",     name: "Иодид натрия",       colorHex: "#EDE9FE", group: .compounds),
        Reagent(symbol: "KI",      name: "Иодид калия",        colorHex: "#EDE9FE", group: .compounds),
        Reagent(symbol: "AgI",     name: "Иодид серебра",      colorHex: "#FEF08A", group: .compounds),
        Reagent(symbol: "NaF",     name: "Фторид натрия",      colorHex: "#BBF7D0", group: .compounds),
        Reagent(symbol: "KF",      name: "Фторид калия",       colorHex: "#BBF7D0", group: .compounds),
        Reagent(symbol: "LiF",     name: "Фторид лития",       colorHex: "#BBF7D0", group: .compounds),
        Reagent(symbol: "CaF2",    name: "Фторид кальция",     colorHex: "#BBF7D0", group: .compounds),
        Reagent(symbol: "BaF2",    name: "Фторид бария",       colorHex: "#BBF7D0", group: .compounds),
        Reagent(symbol: "Na2S",    name: "Сульфид натрия",     colorHex: "#FDE68A", group: .compounds),
        Reagent(symbol: "K2S",     name: "Сульфид калия",      colorHex: "#FDE68A", group: .compounds),
        Reagent(symbol: "FeS",     name: "Сульфид железа(II)", colorHex: "#3F3F46", group: .compounds),
        Reagent(symbol: "CuS",     name: "Сульфид меди(II)",   colorHex: "#0F172A", group: .compounds),
        Reagent(symbol: "ZnS",     name: "Сульфид цинка",      colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "PbS",     name: "Сульфид свинца",     colorHex: "#1E293B", group: .compounds),
        Reagent(symbol: "Ag2S",    name: "Сульфид серебра",    colorHex: "#0C0A09", group: .compounds),
        Reagent(symbol: "CdS",     name: "Сульфид кадмия",     colorHex: "#FEF08A", group: .compounds),
        Reagent(symbol: "HgS",     name: "Сульфид ртути(II)",  colorHex: "#1C1917", group: .compounds),
        Reagent(symbol: "NiS",     name: "Сульфид никеля",     colorHex: "#1F2937", group: .compounds),
        Reagent(symbol: "CoS",     name: "Сульфид кобальта",   colorHex: "#1F2937", group: .compounds),
        Reagent(symbol: "MnS",     name: "Сульфид марганца",   colorHex: "#7E22CE", group: .compounds),
        Reagent(symbol: "Na2SO4",  name: "Сульфат натрия",     colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "K2SO4",   name: "Сульфат калия",      colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "CuSO4",   name: "Сульфат меди(II)",   colorHex: "#06B6D4", group: .compounds),
        Reagent(symbol: "ZnSO4",   name: "Сульфат цинка",      colorHex: "#E0E7FF", group: .compounds),
        Reagent(symbol: "FeSO4",   name: "Сульфат железа(II)", colorHex: "#A3E635", group: .compounds),
        Reagent(symbol: "Fe2(SO4)3",name:"Сульфат железа(III)",colorHex: "#92400E", group: .compounds),
        Reagent(symbol: "BaSO4",   name: "Сульфат бария",      colorHex: "#FFFFFF", group: .compounds),
        Reagent(symbol: "MgSO4",   name: "Сульфат магния",     colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "CaSO4",   name: "Сульфат кальция",    colorHex: "#F1F5F9", group: .compounds),
        Reagent(symbol: "NiSO4",   name: "Сульфат никеля",     colorHex: "#65A30D", group: .compounds),
        Reagent(symbol: "CoSO4",   name: "Сульфат кобальта",   colorHex: "#1D4ED8", group: .compounds),
        Reagent(symbol: "MnSO4",   name: "Сульфат марганца",   colorHex: "#7E22CE", group: .compounds),
        Reagent(symbol: "CdSO4",   name: "Сульфат кадмия",     colorHex: "#71717A", group: .compounds),
        Reagent(symbol: "AgNO3",   name: "Нитрат серебра",     colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "NaNO3",   name: "Нитрат натрия",      colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "KNO3",    name: "Нитрат калия",       colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "Cu(NO3)2",name: "Нитрат меди(II)",    colorHex: "#0E7490", group: .compounds),
        Reagent(symbol: "Pb(NO3)2",name: "Нитрат свинца",      colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "Ba(NO3)2",name: "Нитрат бария",       colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "Ca(NO3)2",name: "Нитрат кальция",     colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "Na2CO3",  name: "Карбонат натрия",    colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "K2CO3",   name: "Карбонат калия",     colorHex: "#E5E7EB", group: .compounds),
        Reagent(symbol: "CaCO3",   name: "Карбонат кальция",   colorHex: "#F1F5F9", group: .compounds),
        Reagent(symbol: "BaCO3",   name: "Карбонат бария",     colorHex: "#F1F5F9", group: .compounds),
        Reagent(symbol: "MgCO3",   name: "Карбонат магния",    colorHex: "#F1F5F9", group: .compounds),
        Reagent(symbol: "CuCO3",   name: "Карбонат меди(II)",  colorHex: "#0E7490", group: .compounds),
        Reagent(symbol: "NaHCO3",  name: "Гидрокарбонат натрия",colorHex:"#E5E7EB", group: .compounds),
        Reagent(symbol: "Na3PO4",  name: "Фосфат натрия",      colorHex: "#FED7AA", group: .compounds),
        Reagent(symbol: "Ca3(PO4)2",name:"Фосфат кальция",     colorHex: "#FED7AA", group: .compounds),
        Reagent(symbol: "NH4Cl",   name: "Хлорид аммония",     colorHex: "#F1F5F9", group: .compounds),
        Reagent(symbol: "NH4NO3",  name: "Нитрат аммония",     colorHex: "#F1F5F9", group: .compounds),
        Reagent(symbol: "(NH4)2SO4",name:"Сульфат аммония",    colorHex: "#F1F5F9", group: .compounds),
        Reagent(symbol: "KMnO4",   name: "Перманганат калия",  colorHex: "#7E22CE", group: .compounds),
        Reagent(symbol: "K2Cr2O7", name: "Дихромат калия",     colorHex: "#EA580C", group: .compounds),
        Reagent(symbol: "CaC2",    name: "Карбид кальция",     colorHex: "#1F2937", group: .compounds),
        Reagent(symbol: "Al4C3",   name: "Карбид алюминия",    colorHex: "#1F2937", group: .compounds),
        Reagent(symbol: "Li3N",    name: "Нитрид лития",       colorHex: "#3B82F6", group: .compounds),
        Reagent(symbol: "Mg3N2",   name: "Нитрид магния",      colorHex: "#3B82F6", group: .compounds),
        Reagent(symbol: "Ca3N2",   name: "Нитрид кальция",     colorHex: "#3B82F6", group: .compounds),
        Reagent(symbol: "Ca3P2",   name: "Фосфид кальция",     colorHex: "#F97316", group: .compounds),
        Reagent(symbol: "Mg2Si",   name: "Силицид магния",     colorHex: "#A8A29E", group: .compounds),
        Reagent(symbol: "NaH",     name: "Гидрид натрия",      colorHex: "#FF6B6B", group: .compounds),
        Reagent(symbol: "LiH",     name: "Гидрид лития",       colorHex: "#FF6B6B", group: .compounds),
        Reagent(symbol: "CaH2",    name: "Гидрид кальция",     colorHex: "#FF6B6B", group: .compounds),

        // ============ ОРГАНИКА ============
        Reagent(symbol: "CH4",     name: "Метан",              colorHex: "#84CC16", group: .organic),
        Reagent(symbol: "C2H6",    name: "Этан",               colorHex: "#7DD3FC", group: .organic),
        Reagent(symbol: "C3H8",    name: "Пропан",             colorHex: "#38BDF8", group: .organic),
        Reagent(symbol: "C4H10",   name: "Бутан",              colorHex: "#0EA5E9", group: .organic),
        Reagent(symbol: "C2H4",    name: "Этилен",             colorHex: "#65A30D", group: .organic),
        Reagent(symbol: "C3H6",    name: "Пропилен",           colorHex: "#4D7C0F", group: .organic),
        Reagent(symbol: "C2H2",    name: "Ацетилен",           colorHex: "#4D7C0F", group: .organic),
        Reagent(symbol: "C6H6",    name: "Бензол",             colorHex: "#FB923C", group: .organic),
        Reagent(symbol: "C6H12",   name: "Циклогексан",        colorHex: "#FB923C", group: .organic),
        Reagent(symbol: "C6H5Br",  name: "Бромбензол",         colorHex: "#FB923C", group: .organic),
        Reagent(symbol: "C6H5OH",  name: "Фенол",              colorHex: "#FED7AA", group: .organic),
        Reagent(symbol: "C6H5ONa", name: "Фенолят натрия",     colorHex: "#FED7AA", group: .organic),
        Reagent(symbol: "C6H2Br3OH",name:"2,4,6-трибромфенол", colorHex: "#FEF3C7", group: .organic),
        Reagent(symbol: "CH3OH",   name: "Метанол",            colorHex: "#BEF264", group: .organic),
        Reagent(symbol: "C2H5OH",  name: "Этанол",             colorHex: "#A3E635", group: .organic),
        Reagent(symbol: "CH3COOH", name: "Уксусная кислота",   colorHex: "#BEF264", group: .organic),
        Reagent(symbol: "CH3CHO",  name: "Ацетальдегид",       colorHex: "#FDE68A", group: .organic),
        Reagent(symbol: "HCHO",    name: "Формальдегид",       colorHex: "#FDE68A", group: .organic),
        Reagent(symbol: "CH3Cl",   name: "Хлорметан",          colorHex: "#FEF08A", group: .organic),
        Reagent(symbol: "C2H5Cl",  name: "Хлорэтан",           colorHex: "#FEF08A", group: .organic),
        Reagent(symbol: "C2H5Br",  name: "Бромэтан",           colorHex: "#FEE2E2", group: .organic),
        Reagent(symbol: "C2H4Br2", name: "1,2-дибромэтан",     colorHex: "#FEE2E2", group: .organic),
        Reagent(symbol: "C2H2Br2", name: "1,2-дибромэтен",     colorHex: "#FEE2E2", group: .organic),
        Reagent(symbol: "C2H5ONa", name: "Этилат натрия",      colorHex: "#A3E635", group: .organic),
        Reagent(symbol: "CH3ONa",  name: "Метилат натрия",     colorHex: "#BEF264", group: .organic),
        Reagent(symbol: "CH3COONa",name: "Ацетат натрия",      colorHex: "#BEF264", group: .organic),
        Reagent(symbol: "CH3COOK", name: "Ацетат калия",       colorHex: "#BEF264", group: .organic),
        Reagent(symbol: "CH3COOC2H5",name:"Этилацетат",        colorHex: "#FDE68A", group: .organic),
        Reagent(symbol: "C6H12O6", name: "Глюкоза",            colorHex: "#FEF3C7", group: .organic),
        Reagent(symbol: "C12H22O11",name:"Сахароза",           colorHex: "#FEF9C3", group: .organic),
    ]

    static func findReagent(by symbol: String) -> Reagent? {
        return reagents.first { $0.symbol == symbol }
    }

    // MARK: - ВСЕ РЕАКЦИИ
    static let reactions: [ChemicalReaction] = [

        // ============================================================
        // 1. МЕТАЛЛ + КИСЛОРОД → ОКСИД
        // ============================================================
        ChemicalReaction(reagents: ["Li","O"], products: ["Li2O"], productNames: ["Оксид лития"],
            equation: "4Li + O₂ → 2Li₂O", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Na","O"], products: ["Na2O"], productNames: ["Оксид натрия"],
            equation: "4Na + O₂ → 2Na₂O", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["K","O"], products: ["K2O"], productNames: ["Оксид калия"],
            equation: "4K + O₂ → 2K₂O", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Rb","O"], products: ["Rb2O"], productNames: ["Оксид рубидия"],
            equation: "4Rb + O₂ → 2Rb₂O", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Cs","O"], products: ["Cs2O"], productNames: ["Оксид цезия"],
            equation: "4Cs + O₂ → 2Cs₂O", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Be","O"], products: ["BeO"], productNames: ["Оксид бериллия"],
            equation: "2Be + O₂ → 2BeO", effect: .flash, effectColorHex: "#FFFFFF",
            warning: "⚠️ Пыль бериллия и его соединений крайне токсична!"),
        ChemicalReaction(reagents: ["Mg","O"], products: ["MgO"], productNames: ["Оксид магния"],
            equation: "2Mg + O₂ → 2MgO", effect: .flash, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["Ca","O"], products: ["CaO"], productNames: ["Оксид кальция"],
            equation: "2Ca + O₂ → 2CaO", effect: .glow, effectColorHex: "#FCD34D"),
        ChemicalReaction(reagents: ["Sr","O"], products: ["SrO"], productNames: ["Оксид стронция"],
            equation: "2Sr + O₂ → 2SrO", effect: .glow, effectColorHex: "#FCD34D"),
        ChemicalReaction(reagents: ["Ba","O"], products: ["BaO"], productNames: ["Оксид бария"],
            equation: "2Ba + O₂ → 2BaO", effect: .glow, effectColorHex: "#FCD34D"),
        ChemicalReaction(reagents: ["Al","O"], products: ["Al2O3"], productNames: ["Оксид алюминия"],
            equation: "4Al + 3O₂ → 2Al₂O₃", effect: .flash, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["Fe","O"], products: ["Fe2O3"], productNames: ["Оксид железа(III)"],
            equation: "4Fe + 3O₂ → 2Fe₂O₃", effect: .explosion, effectColorHex: "#F97316",
            warning: "⚠️ Горение железа в кислороде — работать с тонкой проволокой под тягой."),
        ChemicalReaction(reagents: ["Cu","O"], products: ["CuO"], productNames: ["Оксид меди(II)"],
            equation: "2Cu + O₂ → 2CuO", effect: .colorChange, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Zn","O"], products: ["ZnO"], productNames: ["Оксид цинка"],
            equation: "2Zn + O₂ → 2ZnO", effect: .glow, effectColorHex: "#E5E7EB"),
        ChemicalReaction(reagents: ["Mn","O"], products: ["MnO2"], productNames: ["Оксид марганца(IV)"],
            equation: "Mn + O₂ → MnO₂", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Pb","O"], products: ["PbO"], productNames: ["Оксид свинца(II)"],
            equation: "2Pb + O₂ → 2PbO", effect: .glow, effectColorHex: "#FCD34D"),
        ChemicalReaction(reagents: ["Cr","O"], products: ["Cr2O3"], productNames: ["Оксид хрома(III)"],
            equation: "4Cr + 3O₂ → 2Cr₂O₃", effect: .glow, effectColorHex: "#065F46"),
        ChemicalReaction(reagents: ["Sn","O"], products: ["SnO2"], productNames: ["Оксид олова(IV)"],
            equation: "Sn + O₂ → SnO₂", effect: .glow, effectColorHex: "#D4D4D8"),
        ChemicalReaction(reagents: ["Ni","O"], products: ["NiO"], productNames: ["Оксид никеля(II)"],
            equation: "2Ni + O₂ → 2NiO", effect: .glow, effectColorHex: "#65A30D"),
        ChemicalReaction(reagents: ["Co","O"], products: ["CoO"], productNames: ["Оксид кобальта(II)"],
            equation: "2Co + O₂ → 2CoO", effect: .glow, effectColorHex: "#1D4ED8"),
        ChemicalReaction(reagents: ["Ag","O"], products: ["Ag2O"], productNames: ["Оксид серебра(I)"],
            equation: "4Ag + O₂ → 2Ag₂O", effect: .colorChange, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Ti","O"], products: ["TiO2"], productNames: ["Оксид титана(IV)"],
            equation: "Ti + O₂ → TiO₂ (t°)", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["V","O"], products: ["V2O5"], productNames: ["Оксид ванадия(V)"],
            equation: "4V + 5O₂ → 2V₂O₅", effect: .flash, effectColorHex: "#F97316"),

        // ============================================================
        // 2. НЕМЕТАЛЛ + КИСЛОРОД
        // ============================================================
        ChemicalReaction(reagents: ["H","O"], products: ["H2O"], productNames: ["Вода"],
            equation: "2H₂ + O₂ → 2H₂O", effect: .explosion, effectColorHex: "#FCD34D",
            warning: "🚨 Гремучий газ! Смесь водорода с кислородом взрывается от искры."),
        ChemicalReaction(reagents: ["B","O"], products: ["B2O3"], productNames: ["Оксид бора"],
            equation: "4B + 3O₂ → 2B₂O₃", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["C","O"], products: ["CO2"], productNames: ["Оксид углерода(IV)"],
            equation: "C + O₂ → CO₂", effect: .glow, effectColorHex: "#F97316"),
        ChemicalReaction(reagents: ["Si","O"], products: ["SiO2"], productNames: ["Оксид кремния"],
            equation: "Si + O₂ → SiO₂", effect: .glow, effectColorHex: "#A8A29E"),
        ChemicalReaction(reagents: ["N","O"], products: ["NO"], productNames: ["Оксид азота(II)"],
            equation: "N₂ + O₂ → 2NO (t°>2000°C)", effect: .glow, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["P","O"], products: ["P2O5"], productNames: ["Оксид фосфора(V)"],
            equation: "4P + 5O₂ → 2P₂O₅", effect: .flash, effectColorHex: "#FEF08A",
            warning: "⚠️ Белый фосфор самовоспламеняется на воздухе!"),
        ChemicalReaction(reagents: ["S","O"], products: ["SO2"], productNames: ["Оксид серы(IV)"],
            equation: "S + O₂ → SO₂", effect: .gas, effectColorHex: "#CBD5E1",
            warning: "⚠️ SO₂ токсичен, работать под тягой."),
        ChemicalReaction(reagents: ["As","O"], products: ["As2O3"], productNames: ["Оксид мышьяка(III)"],
            equation: "4As + 3O₂ → 2As₂O₃", effect: .glow, effectColorHex: "#7C3AED",
            warning: "🚨 As₂O₃ — сильный яд!"),
        ChemicalReaction(reagents: ["Se","O"], products: ["SeO2"], productNames: ["Оксид селена(IV)"],
            equation: "Se + O₂ → SeO₂", effect: .glow, effectColorHex: "#CA8A04"),
        ChemicalReaction(reagents: ["Te","O"], products: ["TeO2"], productNames: ["Оксид теллура(IV)"],
            equation: "Te + O₂ → TeO₂", effect: .glow, effectColorHex: "#A16207"),
        ChemicalReaction(reagents: ["Sb","O"], products: ["Sb2O3"], productNames: ["Оксид сурьмы(III)"],
            equation: "4Sb + 3O₂ → 2Sb₂O₃", effect: .glow, effectColorHex: "#525252"),
        ChemicalReaction(reagents: ["Bi","O"], products: ["Bi2O3"], productNames: ["Оксид висмута(III)"],
            equation: "4Bi + 3O₂ → 2Bi₂O₃", effect: .glow, effectColorHex: "#A78BFA"),
        ChemicalReaction(reagents: ["Ge","O"], products: ["GeO2"], productNames: ["Оксид германия(IV)"],
            equation: "Ge + O₂ → GeO₂", effect: .glow, effectColorHex: "#525252"),
        ChemicalReaction(reagents: ["Ga","O"], products: ["Ga2O3"], productNames: ["Оксид галлия(III)"],
            equation: "4Ga + 3O₂ → 2Ga₂O₃", effect: .glow, effectColorHex: "#64748B"),

        // ============================================================
        // 3. МЕТАЛЛ + ВОДА
        // ============================================================
        ChemicalReaction(reagents: ["Li","H2O"], products: ["LiOH"], productNames: ["Гидроксид лития"],
            equation: "2Li + 2H₂O → 2LiOH + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Na","H2O"], products: ["NaOH"], productNames: ["Гидроксид натрия"],
            equation: "2Na + 2H₂O → 2NaOH + H₂↑", effect: .explosion, effectColorHex: "#F97316",
            warning: "⚠️ Натрий бурно реагирует с водой, водород может воспламениться!"),
        ChemicalReaction(reagents: ["K","H2O"], products: ["KOH"], productNames: ["Гидроксид калия"],
            equation: "2K + 2H₂O → 2KOH + H₂↑", effect: .explosion, effectColorHex: "#DC2626",
            warning: "🚨 Калий с водой — ВЗРЫВ!"),
        ChemicalReaction(reagents: ["Rb","H2O"], products: ["RbOH"], productNames: ["Гидроксид рубидия"],
            equation: "2Rb + 2H₂O → 2RbOH + H₂↑", effect: .explosion, effectColorHex: "#DC2626",
            warning: "🚨 Рубидий с водой взрывается!"),
        ChemicalReaction(reagents: ["Cs","H2O"], products: ["CsOH"], productNames: ["Гидроксид цезия"],
            equation: "2Cs + 2H₂O → 2CsOH + H₂↑", effect: .explosion, effectColorHex: "#DC2626",
            warning: "🚨 Цезий с водой взрывается мгновенно!"),
        ChemicalReaction(reagents: ["Ca","H2O"], products: ["Ca(OH)2"], productNames: ["Гидроксид кальция"],
            equation: "Ca + 2H₂O → Ca(OH)₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Sr","H2O"], products: ["Sr(OH)2"], productNames: ["Гидроксид стронция"],
            equation: "Sr + 2H₂O → Sr(OH)₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Ba","H2O"], products: ["Ba(OH)2"], productNames: ["Гидроксид бария"],
            equation: "Ba + 2H₂O → Ba(OH)₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE",
            warning: "⚠️ Соединения бария ядовиты!"),

        // ============================================================
        // 4. МЕТАЛЛ + КИСЛОТА
        // ============================================================
        ChemicalReaction(reagents: ["Li","HCl"], products: ["LiCl"], productNames: ["Хлорид лития"],
            equation: "2Li + 2HCl → 2LiCl + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Na","HCl"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "2Na + 2HCl → 2NaCl + H₂↑", effect: .explosion, effectColorHex: "#DC2626",
            warning: "🚨 Натрий с кислотой — взрыв!"),
        ChemicalReaction(reagents: ["K","HCl"], products: ["KCl"], productNames: ["Хлорид калия"],
            equation: "2K + 2HCl → 2KCl + H₂↑", effect: .explosion, effectColorHex: "#DC2626",
            warning: "🚨 Калий с кислотой — взрыв!"),
        ChemicalReaction(reagents: ["Mg","HCl"], products: ["MgCl2"], productNames: ["Хлорид магния"],
            equation: "Mg + 2HCl → MgCl₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Zn","HCl"], products: ["ZnCl2"], productNames: ["Хлорид цинка"],
            equation: "Zn + 2HCl → ZnCl₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Fe","HCl"], products: ["FeCl2"], productNames: ["Хлорид железа(II)"],
            equation: "Fe + 2HCl → FeCl₂ + H₂↑", effect: .gas, effectColorHex: "#DCFCE7"),
        ChemicalReaction(reagents: ["Al","HCl"], products: ["AlCl3"], productNames: ["Хлорид алюминия"],
            equation: "2Al + 6HCl → 2AlCl₃ + 3H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Ca","HCl"], products: ["CaCl2"], productNames: ["Хлорид кальция"],
            equation: "Ca + 2HCl → CaCl₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Ba","HCl"], products: ["BaCl2"], productNames: ["Хлорид бария"],
            equation: "Ba + 2HCl → BaCl₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Ni","HCl"], products: ["NiCl2"], productNames: ["Хлорид никеля(II)"],
            equation: "Ni + 2HCl → NiCl₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Co","HCl"], products: ["CoCl2"], productNames: ["Хлорид кобальта(II)"],
            equation: "Co + 2HCl → CoCl₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Sn","HCl"], products: ["SnCl2"], productNames: ["Хлорид олова(II)"],
            equation: "Sn + 2HCl → SnCl₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Mg","H2SO4"], products: ["MgSO4"], productNames: ["Сульфат магния"],
            equation: "Mg + H₂SO₄ → MgSO₄ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Zn","H2SO4"], products: ["ZnSO4"], productNames: ["Сульфат цинка"],
            equation: "Zn + H₂SO₄ → ZnSO₄ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Fe","H2SO4"], products: ["FeSO4"], productNames: ["Сульфат железа(II)"],
            equation: "Fe + H₂SO₄ → FeSO₄ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Ba","H2SO4"], products: ["BaSO4"], productNames: ["Сульфат бария"],
            equation: "Ba + H₂SO₄ → BaSO₄↓ + H₂↑", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["Ca","H2SO4"], products: ["CaSO4"], productNames: ["Сульфат кальция"],
            equation: "Ca + H₂SO₄ → CaSO₄↓ + H₂↑", effect: .precipitateWhite, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["Zn","HNO3"], products: ["ZnNO3"], productNames: ["Нитрат цинка"],
            equation: "3Zn + 8HNO₃(разб.) → 3Zn(NO₃)₂ + 2NO↑ + 4H₂O",
            effect: .gas, effectColorHex: "#F59E0B",
            warning: "⚠️ Выделяются токсичные оксиды азота! Только под тягой."),

        // ============================================================
        // 5. МЕТАЛЛ + ГАЛОГЕН
        // ============================================================
        ChemicalReaction(reagents: ["Na","Cl"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "2Na + Cl₂ → 2NaCl", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["K","Cl"], products: ["KCl"], productNames: ["Хлорид калия"],
            equation: "2K + Cl₂ → 2KCl", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Rb","Cl"], products: ["RbCl"], productNames: ["Хлорид рубидия"],
            equation: "2Rb + Cl₂ → 2RbCl", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Cs","Cl"], products: ["CsCl"], productNames: ["Хлорид цезия"],
            equation: "2Cs + Cl₂ → 2CsCl", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Ca","Cl"], products: ["CaCl2"], productNames: ["Хлорид кальция"],
            equation: "Ca + Cl₂ → CaCl₂", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Sr","Cl"], products: ["SrCl2"], productNames: ["Хлорид стронция"],
            equation: "Sr + Cl₂ → SrCl₂", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Cu","Cl"], products: ["CuCl2"], productNames: ["Хлорид меди(II)"],
            equation: "Cu + Cl₂ → CuCl₂", effect: .glow, effectColorHex: "#0891B2"),
        ChemicalReaction(reagents: ["Fe","Cl"], products: ["FeCl3"], productNames: ["Хлорид железа(III)"],
            equation: "2Fe + 3Cl₂ → 2FeCl₃", effect: .flash, effectColorHex: "#F97316"),
        ChemicalReaction(reagents: ["Al","Cl"], products: ["AlCl3"], productNames: ["Хлорид алюминия"],
            equation: "2Al + 3Cl₂ → 2AlCl₃", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Zn","Cl"], products: ["ZnCl2"], productNames: ["Хлорид цинка"],
            equation: "Zn + Cl₂ → ZnCl₂", effect: .glow, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Ni","Cl"], products: ["NiCl2"], productNames: ["Хлорид никеля(II)"],
            equation: "Ni + Cl₂ → NiCl₂", effect: .glow, effectColorHex: "#65A30D"),
        ChemicalReaction(reagents: ["Co","Cl"], products: ["CoCl2"], productNames: ["Хлорид кобальта(II)"],
            equation: "Co + Cl₂ → CoCl₂", effect: .glow, effectColorHex: "#1D4ED8"),
        ChemicalReaction(reagents: ["Cr","Cl"], products: ["CrCl3"], productNames: ["Хлорид хрома(III)"],
            equation: "2Cr + 3Cl₂ → 2CrCl₃", effect: .flash, effectColorHex: "#065F46"),
        ChemicalReaction(reagents: ["Mn","Cl"], products: ["MnCl2"], productNames: ["Хлорид марганца(II)"],
            equation: "Mn + Cl₂ → MnCl₂", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Ti","Cl"], products: ["TiCl4"], productNames: ["Тетрахлорид титана"],
            equation: "Ti + 2Cl₂ → TiCl₄", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["V","Cl"], products: ["VCl5"], productNames: ["Хлорид ванадия(V)"],
            equation: "2V + 5Cl₂ → 2VCl₅", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Sn","Cl"], products: ["SnCl4"], productNames: ["Тетрахлорид олова"],
            equation: "Sn + 2Cl₂ → SnCl₄", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Pb","Cl"], products: ["PbCl2"], productNames: ["Хлорид свинца(II)"],
            equation: "Pb + Cl₂ → PbCl₂", effect: .glow, effectColorHex: "#64748B"),
        ChemicalReaction(reagents: ["Sb","Cl"], products: ["SbCl3"], productNames: ["Хлорид сурьмы(III)"],
            equation: "2Sb + 3Cl₂ → 2SbCl₃", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Bi","Cl"], products: ["BiCl3"], productNames: ["Хлорид висмута(III)"],
            equation: "2Bi + 3Cl₂ → 2BiCl₃", effect: .glow, effectColorHex: "#A78BFA"),
        ChemicalReaction(reagents: ["Ga","Cl"], products: ["GaCl3"], productNames: ["Хлорид галлия(III)"],
            equation: "2Ga + 3Cl₂ → 2GaCl₃", effect: .glow, effectColorHex: "#64748B"),
        ChemicalReaction(reagents: ["Ge","Cl"], products: ["GeCl4"], productNames: ["Тетрахлорид германия"],
            equation: "Ge + 2Cl₂ → GeCl₄", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Be","Cl"], products: ["BeCl2"], productNames: ["Хлорид бериллия"],
            equation: "Be + Cl₂ → BeCl₂", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["H","Cl"], products: ["HCl"], productNames: ["Хлороводород"],
            equation: "H₂ + Cl₂ → 2HCl (свет)", effect: .explosion, effectColorHex: "#FEF08A",
            warning: "⚠️ Реакция идёт на свету со взрывом. HCl — едкий газ."),
        ChemicalReaction(reagents: ["P","Cl"], products: ["PCl3"], productNames: ["Хлорид фосфора(III)"],
            equation: "2P + 3Cl₂ → 2PCl₃", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["S","Cl"], products: ["SCl2"], productNames: ["Хлорид серы(II)"],
            equation: "S + Cl₂ → SCl₂", effect: .gas, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Si","Cl"], products: ["SiCl4"], productNames: ["Тетрахлорид кремния"],
            equation: "Si + 2Cl₂ → SiCl₄", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["B","Cl"], products: ["BCl3"], productNames: ["Трихлорид бора"],
            equation: "2B + 3Cl₂ → 2BCl₃", effect: .glow, effectColorHex: "#4ADE80"),
        ChemicalReaction(reagents: ["Xe","F"], products: ["XeF4"], productNames: ["Фторид ксенона(IV)"],
            equation: "Xe + 2F₂ → XeF₄", effect: .flash, effectColorHex: "#22C55E"),

        // --- ФТОР ---
        ChemicalReaction(reagents: ["H","F"], products: ["HF"], productNames: ["Фтороводород"],
            equation: "H₂ + F₂ → 2HF", effect: .explosion, effectColorHex: "#22C55E",
            warning: "🚨 Взрыв даже на холоде! HF крайне токсичен."),
        ChemicalReaction(reagents: ["Na","F"], products: ["NaF"], productNames: ["Фторид натрия"],
            equation: "2Na + F₂ → 2NaF", effect: .explosion, effectColorHex: "#22C55E",
            warning: "🚨 Фтор — самый активный неметалл, реакция со взрывом!"),
        ChemicalReaction(reagents: ["K","F"], products: ["KF"], productNames: ["Фторид калия"],
            equation: "2K + F₂ → 2KF", effect: .explosion, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Li","F"], products: ["LiF"], productNames: ["Фторид лития"],
            equation: "2Li + F₂ → 2LiF", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Ca","F"], products: ["CaF2"], productNames: ["Фторид кальция"],
            equation: "Ca + F₂ → CaF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Ba","F"], products: ["BaF2"], productNames: ["Фторид бария"],
            equation: "Ba + F₂ → BaF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Sr","F"], products: ["SrF2"], productNames: ["Фторид стронция"],
            equation: "Sr + F₂ → SrF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Be","F"], products: ["BeF2"], productNames: ["Фторид бериллия"],
            equation: "Be + F₂ → BeF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["B","F"], products: ["BF3"], productNames: ["Трифторид бора"],
            equation: "2B + 3F₂ → 2BF₃", effect: .flash, effectColorHex: "#22C55E",
            warning: "⚠️ Фтор очень активен! Реакция идёт со вспышкой, работать под тягой."),
        ChemicalReaction(reagents: ["Si","F"], products: ["SiF4"], productNames: ["Тетрафторид кремния"],
            equation: "Si + 2F₂ → SiF₄", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["S","F"], products: ["SF6"], productNames: ["Фторид серы(VI)"],
            equation: "S + 3F₂ → SF₆", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Sn","F"], products: ["SnF4"], productNames: ["Тетрафторид олова"],
            equation: "Sn + 2F₂ → SnF₄", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Pb","F"], products: ["PbF2"], productNames: ["Фторид свинца(II)"],
            equation: "Pb + F₂ → PbF₂", effect: .glow, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Zn","F"], products: ["ZnF2"], productNames: ["Фторид цинка"],
            equation: "Zn + F₂ → ZnF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Ni","F"], products: ["NiF2"], productNames: ["Фторид никеля(II)"],
            equation: "Ni + F₂ → NiF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Co","F"], products: ["CoF2"], productNames: ["Фторид кобальта(II)"],
            equation: "Co + F₂ → CoF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["HF","NaOH"], products: ["NaF"], productNames: ["Фторид натрия"],
            equation: "HF + NaOH → NaF + H₂O", effect: .glow, effectColorHex: "#BBF7D0",
            warning: "⚠️ Плавиковая кислота HF разъедает стекло и очень токсична!"),

        // --- БРОМ ---
        ChemicalReaction(reagents: ["Na","Br"], products: ["NaBr"], productNames: ["Бромид натрия"],
            equation: "2Na + Br₂ → 2NaBr", effect: .flash, effectColorHex: "#FEE2E2"),
        ChemicalReaction(reagents: ["K","Br"], products: ["KBr"], productNames: ["Бромид калия"],
            equation: "2K + Br₂ → 2KBr", effect: .flash, effectColorHex: "#FEE2E2"),
        ChemicalReaction(reagents: ["H","Br"], products: ["HBr"], productNames: ["Бромоводород"],
            equation: "H₂ + Br₂ → 2HBr", effect: .glow, effectColorHex: "#FEE2E2"),
        ChemicalReaction(reagents: ["Zn","Br"], products: ["ZnBr2"], productNames: ["Бромид цинка"],
            equation: "Zn + Br₂ → ZnBr₂", effect: .glow, effectColorHex: "#B91C1C"),
        ChemicalReaction(reagents: ["B","Br"], products: ["BBr3"], productNames: ["Трибромид бора"],
            equation: "2B + 3Br₂ → 2BBr₃", effect: .glow, effectColorHex: "#B91C1C"),
        ChemicalReaction(reagents: ["Ba","Br"], products: ["BaBr2"], productNames: ["Бромид бария"],
            equation: "Ba + Br₂ → BaBr₂", effect: .glow, effectColorHex: "#B91C1C"),
        ChemicalReaction(reagents: ["Si","Br"], products: ["SiBr4"], productNames: ["Тетрабромид кремния"],
            equation: "Si + 2Br₂ → SiBr₄", effect: .glow, effectColorHex: "#B91C1C"),

        // --- ИОД ---
        ChemicalReaction(reagents: ["Na","I"], products: ["NaI"], productNames: ["Иодид натрия"],
            equation: "2Na + I₂ → 2NaI", effect: .glow, effectColorHex: "#EDE9FE"),
        ChemicalReaction(reagents: ["K","I"], products: ["KI"], productNames: ["Иодид калия"],
            equation: "2K + I₂ → 2KI", effect: .glow, effectColorHex: "#EDE9FE"),
        ChemicalReaction(reagents: ["H","I"], products: ["HI"], productNames: ["Иодоводород"],
            equation: "H₂ + I₂ ⇄ 2HI", effect: .glow, effectColorHex: "#EDE9FE"),
        ChemicalReaction(reagents: ["Li","I"], products: ["LiI"], productNames: ["Иодид лития"],
            equation: "2Li + I₂ → 2LiI", effect: .glow, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Zn","I"], products: ["ZnI2"], productNames: ["Иодид цинка"],
            equation: "Zn + I₂ → ZnI₂", effect: .glow, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Ba","I"], products: ["BaI2"], productNames: ["Иодид бария"],
            equation: "Ba + I₂ → BaI₂", effect: .glow, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["B","I"], products: ["BI3"], productNames: ["Трииодид бора"],
            equation: "2B + 3I₂ → 2BI₃", effect: .glow, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Si","I"], products: ["SiI4"], productNames: ["Тетраиодид кремния"],
            equation: "Si + 2I₂ → SiI₄", effect: .glow, effectColorHex: "#7C3AED"),

        // ============================================================
        // 6. МЕТАЛЛ + СЕРА
        // ============================================================
        ChemicalReaction(reagents: ["Na","S"], products: ["Na2S"], productNames: ["Сульфид натрия"],
            equation: "2Na + S → Na₂S", effect: .explosion, effectColorHex: "#FDE68A",
            warning: "⚠️ Реакция со вспышкой!"),
        ChemicalReaction(reagents: ["K","S"], products: ["K2S"], productNames: ["Сульфид калия"],
            equation: "2K + S → K₂S", effect: .explosion, effectColorHex: "#FDE68A"),
        ChemicalReaction(reagents: ["Li","S"], products: ["Li2S"], productNames: ["Сульфид лития"],
            equation: "2Li + S → Li₂S", effect: .flash, effectColorHex: "#FDE68A"),
        ChemicalReaction(reagents: ["Fe","S"], products: ["FeS"], productNames: ["Сульфид железа(II)"],
            equation: "Fe + S → FeS", effect: .glow, effectColorHex: "#7C2D12"),
        ChemicalReaction(reagents: ["Cu","S"], products: ["CuS"], productNames: ["Сульфид меди(II)"],
            equation: "Cu + S → CuS", effect: .glow, effectColorHex: "#0F172A"),
        ChemicalReaction(reagents: ["Zn","S"], products: ["ZnS"], productNames: ["Сульфид цинка"],
            equation: "Zn + S → ZnS", effect: .glow, effectColorHex: "#E5E7EB"),
        ChemicalReaction(reagents: ["Pb","S"], products: ["PbS"], productNames: ["Сульфид свинца"],
            equation: "Pb + S → PbS", effect: .glow, effectColorHex: "#1E293B"),
        ChemicalReaction(reagents: ["Ag","S"], products: ["Ag2S"], productNames: ["Сульфид серебра"],
            equation: "2Ag + S → Ag₂S", effect: .colorChange, effectColorHex: "#0C0A09"),
        ChemicalReaction(reagents: ["Ca","S"], products: ["CaS"], productNames: ["Сульфид кальция"],
            equation: "Ca + S → CaS", effect: .glow, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Mg","S"], products: ["MgS"], productNames: ["Сульфид магния"],
            equation: "Mg + S → MgS", effect: .glow, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Al","S"], products: ["Al2S3"], productNames: ["Сульфид алюминия"],
            equation: "2Al + 3S → Al₂S₃", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Ba","S"], products: ["BaS"], productNames: ["Сульфид бария"],
            equation: "Ba + S → BaS (t°)", effect: .glow, effectColorHex: "#FDE68A"),
        ChemicalReaction(reagents: ["Mn","S"], products: ["MnS"], productNames: ["Сульфид марганца(II)"],
            equation: "Mn + S → MnS (t°)", effect: .glow, effectColorHex: "#7E22CE"),
        ChemicalReaction(reagents: ["Cr","S"], products: ["Cr2S3"], productNames: ["Сульфид хрома(III)"],
            equation: "2Cr + 3S → Cr₂S₃ (t°)", effect: .glow, effectColorHex: "#065F46"),
        ChemicalReaction(reagents: ["Ni","S"], products: ["NiS"], productNames: ["Сульфид никеля(II)"],
            equation: "Ni + S → NiS (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Co","S"], products: ["CoS"], productNames: ["Сульфид кобальта(II)"],
            equation: "Co + S → CoS (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Sn","S"], products: ["SnS"], productNames: ["Сульфид олова(II)"],
            equation: "Sn + S → SnS (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Sb","S"], products: ["Sb2S3"], productNames: ["Сульфид сурьмы(III)"],
            equation: "2Sb + 3S → Sb₂S₃", effect: .glow, effectColorHex: "#1E293B"),
        ChemicalReaction(reagents: ["Bi","S"], products: ["Bi2S3"], productNames: ["Сульфид висмута(III)"],
            equation: "2Bi + 3S → Bi₂S₃", effect: .glow, effectColorHex: "#1E293B"),
        ChemicalReaction(reagents: ["As","S"], products: ["As2S3"], productNames: ["Сульфид мышьяка(III)"],
            equation: "2As + 3S → As₂S₃", effect: .glow, effectColorHex: "#FACC15"),
        ChemicalReaction(reagents: ["B","S"], products: ["B2S3"], productNames: ["Сульфид бора"],
            equation: "2B + 3S → B₂S₃ (t°)", effect: .glow, effectColorHex: "#FACC15"),
        ChemicalReaction(reagents: ["Si","S"], products: ["SiS2"], productNames: ["Сульфид кремния"],
            equation: "Si + 2S → SiS₂ (t°)", effect: .glow, effectColorHex: "#FACC15"),

        // ============================================================
        // 7. МЕТАЛЛ + АЗОТ → НИТРИДЫ
        // ============================================================
        ChemicalReaction(reagents: ["Li","N"], products: ["Li3N"], productNames: ["Нитрид лития"],
            equation: "6Li + N₂ → 2Li₃N", effect: .glow, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["Mg","N"], products: ["Mg3N2"], productNames: ["Нитрид магния"],
            equation: "3Mg + N₂ → Mg₃N₂", effect: .glow, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["Ca","N"], products: ["Ca3N2"], productNames: ["Нитрид кальция"],
            equation: "3Ca + N₂ → Ca₃N₂", effect: .glow, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["Ba","N"], products: ["Ba3N2"], productNames: ["Нитрид бария"],
            equation: "3Ba + N₂ → Ba₃N₂ (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Al","N"], products: ["AlN"], productNames: ["Нитрид алюминия"],
            equation: "2Al + N₂ → 2AlN", effect: .glow, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["B","N"], products: ["BN"], productNames: ["Нитрид бора"],
            equation: "2B + N₂ → 2BN (t°)", effect: .glow, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["Si","N"], products: ["Si3N4"], productNames: ["Нитрид кремния"],
            equation: "3Si + 2N₂ → Si₃N₄ (t°)", effect: .glow, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["Ti","N"], products: ["TiN"], productNames: ["Нитрид титана"],
            equation: "2Ti + N₂ → 2TiN (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Cr","N"], products: ["CrN"], productNames: ["Нитрид хрома"],
            equation: "2Cr + N₂ → 2CrN (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Mn","N"], products: ["Mn3N2"], productNames: ["Нитрид марганца"],
            equation: "3Mn + N₂ → Mn₃N₂ (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Zn","N"], products: ["Zn3N2"], productNames: ["Нитрид цинка"],
            equation: "3Zn + N₂ → Zn₃N₂ (t°)", effect: .glow, effectColorHex: "#1F2937"),

        // ============================================================
        // 8. МЕТАЛЛ + ВОДОРОД → ГИДРИДЫ
        // ============================================================
        ChemicalReaction(reagents: ["Li","H"], products: ["LiH"], productNames: ["Гидрид лития"],
            equation: "2Li + H₂ → 2LiH", effect: .glow, effectColorHex: "#FF6B6B"),
        ChemicalReaction(reagents: ["Na","H"], products: ["NaH"], productNames: ["Гидрид натрия"],
            equation: "2Na + H₂ → 2NaH", effect: .glow, effectColorHex: "#FF6B6B"),
        ChemicalReaction(reagents: ["Ca","H"], products: ["CaH2"], productNames: ["Гидрид кальция"],
            equation: "Ca + H₂ → CaH₂", effect: .glow, effectColorHex: "#FF6B6B"),

        // ============================================================
        // 9. НЕМЕТАЛЛ + ВОДОРОД
        // ============================================================
        ChemicalReaction(reagents: ["N","H"], products: ["NH3"], productNames: ["Аммиак"],
            equation: "N₂ + 3H₂ ⇄ 2NH₃ (кат., t°, p)", effect: .gas, effectColorHex: "#A5B4FC"),
        ChemicalReaction(reagents: ["S","H"], products: ["H2S"], productNames: ["Сероводород"],
            equation: "S + H₂ → H₂S", effect: .gas, effectColorHex: "#FACC15",
            warning: "⚠️ H₂S — очень токсичный газ!"),
        ChemicalReaction(reagents: ["C","H"], products: ["CH4"], productNames: ["Метан"],
            equation: "C + 2H₂ → CH₄ (кат., t°)", effect: .glow, effectColorHex: "#84CC16"),
        ChemicalReaction(reagents: ["As","H"], products: ["AsH3"], productNames: ["Арсин"],
            equation: "2As + 3H₂ ⇄ 2AsH₃ (кат.)", effect: .gas, effectColorHex: "#7C3AED",
            warning: "🚨 Арсин AsH₃ — крайне токсичный газ!"),
        ChemicalReaction(reagents: ["Se","H"], products: ["H2Se"], productNames: ["Селеноводород"],
            equation: "Se + H₂ ⇄ H₂Se (t°)", effect: .gas, effectColorHex: "#CA8A04",
            warning: "⚠️ H₂Se очень токсичен!"),
        ChemicalReaction(reagents: ["Te","H"], products: ["H2Te"], productNames: ["Теллуроводород"],
            equation: "Te + H₂ ⇄ H₂Te (t°)", effect: .gas, effectColorHex: "#A16207"),
        ChemicalReaction(reagents: ["Sb","H"], products: ["SbH3"], productNames: ["Стибин"],
            equation: "2Sb + 3H₂ ⇄ 2SbH₃ (кат.)", effect: .gas, effectColorHex: "#525252",
            warning: "🚨 Стибин SbH₃ очень токсичен!"),
        ChemicalReaction(reagents: ["B","H"], products: ["B2H6"], productNames: ["Дибoран"],
            equation: "2B + 3H₂ → B₂H₆ (t°, кат.)", effect: .gas, effectColorHex: "#FF6B6B"),
        ChemicalReaction(reagents: ["Si","H"], products: ["SiH4"], productNames: ["Силан"],
            equation: "Si + 2H₂ → SiH₄ (t°, кат.)", effect: .gas, effectColorHex: "#FF6B6B",
            warning: "⚠️ Силан самовоспламеняется на воздухе!"),

        // ============================================================
        // 10. МЕТАЛЛ + УГЛЕРОД → КАРБИДЫ
        // ============================================================
        ChemicalReaction(reagents: ["Ca","C"], products: ["CaC2"], productNames: ["Карбид кальция"],
            equation: "Ca + 2C → CaC₂ (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Al","C"], products: ["Al4C3"], productNames: ["Карбид алюминия"],
            equation: "4Al + 3C → Al₄C₃ (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Ba","C"], products: ["BaC2"], productNames: ["Карбид бария"],
            equation: "Ba + 2C → BaC₂ (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Ti","C"], products: ["TiC"], productNames: ["Карбид титана"],
            equation: "Ti + C → TiC (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["B","C"], products: ["B4C"], productNames: ["Карбид бора"],
            equation: "4B + C → B₄C (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Si","C"], products: ["SiC"], productNames: ["Карбид кремния"],
            equation: "Si + C → SiC (t°)", effect: .glow, effectColorHex: "#525252"),
        ChemicalReaction(reagents: ["Si","Mg"], products: ["Mg2Si"], productNames: ["Силицид магния"],
            equation: "2Mg + Si → Mg₂Si (t°)", effect: .glow, effectColorHex: "#FEF08A"),

        // ============================================================
        // 11. ОКСИД + ВОДА
        // ============================================================
        ChemicalReaction(reagents: ["Li2O","H2O"], products: ["LiOH"], productNames: ["Гидроксид лития"],
            equation: "Li₂O + H₂O → 2LiOH", effect: .glow, effectColorHex: "#FCD34D"),
        ChemicalReaction(reagents: ["Na2O","H2O"], products: ["NaOH"], productNames: ["Гидроксид натрия"],
            equation: "Na₂O + H₂O → 2NaOH", effect: .glow, effectColorHex: "#FCD34D"),
        ChemicalReaction(reagents: ["K2O","H2O"], products: ["KOH"], productNames: ["Гидроксид калия"],
            equation: "K₂O + H₂O → 2KOH", effect: .glow, effectColorHex: "#FCD34D"),
        ChemicalReaction(reagents: ["CaO","H2O"], products: ["Ca(OH)2"], productNames: ["Гидроксид кальция"],
            equation: "CaO + H₂O → Ca(OH)₂ + Q", effect: .glow, effectColorHex: "#FCD34D",
            warning: "⚠️ Гашение извести — очень экзотермично!"),
        ChemicalReaction(reagents: ["BaO","H2O"], products: ["Ba(OH)2"], productNames: ["Гидроксид бария"],
            equation: "BaO + H₂O → Ba(OH)₂", effect: .glow, effectColorHex: "#FCD34D"),
        ChemicalReaction(reagents: ["B2O3","H2O"], products: ["H3BO3"], productNames: ["Борная кислота"],
            equation: "B₂O₃ + 3H₂O → 2H₃BO₃", effect: .glow, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["SO2","H2O"], products: ["H2SO3"], productNames: ["Сернистая кислота"],
            equation: "SO₂ + H₂O ⇄ H₂SO₃", effect: .colorChange, effectColorHex: "#FCD34D"),
        ChemicalReaction(reagents: ["SO3","H2O"], products: ["H2SO4"], productNames: ["Серная кислота"],
            equation: "SO₃ + H₂O → H₂SO₄ + Q", effect: .explosion, effectColorHex: "#F97316",
            warning: "🚨 Нельзя лить воду в SO₃! Только SO₃ в кислоту!"),
        ChemicalReaction(reagents: ["CO2","H2O"], products: ["H2CO3"], productNames: ["Угольная кислота"],
            equation: "CO₂ + H₂O ⇄ H₂CO₃", effect: .glow, effectColorHex: "#94A3B8"),
        ChemicalReaction(reagents: ["P2O5","H2O"], products: ["H3PO4"], productNames: ["Фосфорная кислота"],
            equation: "P₂O₅ + 3H₂O → 2H₃PO₄", effect: .glow, effectColorHex: "#FBBF24"),
        ChemicalReaction(reagents: ["N2O5","H2O"], products: ["HNO3"], productNames: ["Азотная кислота"],
            equation: "N₂O₅ + H₂O → 2HNO₃", effect: .glow, effectColorHex: "#F59E0B"),

        // ============================================================
        // 12. КИСЛОТА + ОСНОВАНИЕ
        // ============================================================
        ChemicalReaction(reagents: ["NaOH","HCl"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "NaOH + HCl → NaCl + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["KOH","HCl"], products: ["KCl"], productNames: ["Хлорид калия"],
            equation: "KOH + HCl → KCl + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["LiOH","HCl"], products: ["LiCl"], productNames: ["Хлорид лития"],
            equation: "LiOH + HCl → LiCl + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["NaOH","H2SO4"], products: ["Na2SO4"], productNames: ["Сульфат натрия"],
            equation: "2NaOH + H₂SO₄ → Na₂SO₄ + 2H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["KOH","H2SO4"], products: ["K2SO4"], productNames: ["Сульфат калия"],
            equation: "2KOH + H₂SO₄ → K₂SO₄ + 2H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["NaOH","HNO3"], products: ["NaNO3"], productNames: ["Нитрат натрия"],
            equation: "NaOH + HNO₃ → NaNO₃ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["KOH","HNO3"], products: ["KNO3"], productNames: ["Нитрат калия"],
            equation: "KOH + HNO₃ → KNO₃ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["Ca(OH)2","HCl"], products: ["CaCl2"], productNames: ["Хлорид кальция"],
            equation: "Ca(OH)₂ + 2HCl → CaCl₂ + 2H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["Ba(OH)2","HCl"], products: ["BaCl2"], productNames: ["Хлорид бария"],
            equation: "Ba(OH)₂ + 2HCl → BaCl₂ + 2H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["Ba(OH)2","H2SO4"], products: ["BaSO4"], productNames: ["Сульфат бария"],
            equation: "Ba(OH)₂ + H₂SO₄ → BaSO₄↓ + 2H₂O", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["Ca(OH)2","H3PO4"], products: ["Ca3(PO4)2"], productNames: ["Фосфат кальция"],
            equation: "3Ca(OH)₂ + 2H₃PO₄ → Ca₃(PO₄)₂↓ + 6H₂O", effect: .precipitateWhite, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["NaOH","H3PO4"], products: ["Na3PO4"], productNames: ["Фосфат натрия"],
            equation: "3NaOH + H₃PO₄ → Na₃PO₄ + 3H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["Ba(OH)2","HNO3"], products: ["Ba(NO3)2"], productNames: ["Нитрат бария"],
            equation: "Ba(OH)₂ + 2HNO₃ → Ba(NO₃)₂ + 2H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["Ca(OH)2","HNO3"], products: ["Ca(NO3)2"], productNames: ["Нитрат кальция"],
            equation: "Ca(OH)₂ + 2HNO₃ → Ca(NO₃)₂ + 2H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["NH4OH","HCl"], products: ["NH4Cl"], productNames: ["Хлорид аммония"],
            equation: "NH₄OH + HCl → NH₄Cl + H₂O", effect: .glow, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["NH4OH","HNO3"], products: ["NH4NO3"], productNames: ["Нитрат аммония"],
            equation: "NH₄OH + HNO₃ → NH₄NO₃ + H₂O", effect: .glow, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["NH4OH","H2SO4"], products: ["(NH4)2SO4"], productNames: ["Сульфат аммония"],
            equation: "2NH₄OH + H₂SO₄ → (NH₄)₂SO₄ + 2H₂O", effect: .glow, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["NH4OH","H3PO4"], products: ["NH4H2PO4"], productNames: ["Дигидрофосфат аммония"],
            equation: "NH₄OH + H₃PO₄ → NH₄H₂PO₄ + H₂O", effect: .glow, effectColorHex: "#F1F5F9"),

        // ============================================================
        // 13. ОСНОВНЫЙ ОКСИД + КИСЛОТА
        // ============================================================
        ChemicalReaction(reagents: ["CuO","HCl"], products: ["CuCl2"], productNames: ["Хлорид меди(II)"],
            equation: "CuO + 2HCl → CuCl₂ + H₂O", effect: .colorChange, effectColorHex: "#0891B2"),
        ChemicalReaction(reagents: ["CuO","H2SO4"], products: ["CuSO4"], productNames: ["Сульфат меди(II)"],
            equation: "CuO + H₂SO₄ → CuSO₄ + H₂O", effect: .colorChange, effectColorHex: "#06B6D4"),
        ChemicalReaction(reagents: ["CuO","HNO3"], products: ["Cu(NO3)2"], productNames: ["Нитрат меди(II)"],
            equation: "CuO + 2HNO₃ → Cu(NO₃)₂ + H₂O", effect: .colorChange, effectColorHex: "#0E7490"),
        ChemicalReaction(reagents: ["Fe2O3","HCl"], products: ["FeCl3"], productNames: ["Хлорид железа(III)"],
            equation: "Fe₂O₃ + 6HCl → 2FeCl₃ + 3H₂O", effect: .colorChange, effectColorHex: "#B45309"),
        ChemicalReaction(reagents: ["Fe2O3","H2SO4"], products: ["Fe2(SO4)3"], productNames: ["Сульфат железа(III)"],
            equation: "Fe₂O₃ + 3H₂SO₄ → Fe₂(SO₄)₃ + 3H₂O", effect: .colorChange, effectColorHex: "#92400E"),
        ChemicalReaction(reagents: ["MgO","HCl"], products: ["MgCl2"], productNames: ["Хлорид магния"],
            equation: "MgO + 2HCl → MgCl₂ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["MgO","H2SO4"], products: ["MgSO4"], productNames: ["Сульфат магния"],
            equation: "MgO + H₂SO₄ → MgSO₄ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["CaO","HCl"], products: ["CaCl2"], productNames: ["Хлорид кальция"],
            equation: "CaO + 2HCl → CaCl₂ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["CaO","H2SO4"], products: ["CaSO4"], productNames: ["Сульфат кальция"],
            equation: "CaO + H₂SO₄ → CaSO₄↓ + H₂O", effect: .precipitateWhite, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["ZnO","HCl"], products: ["ZnCl2"], productNames: ["Хлорид цинка"],
            equation: "ZnO + 2HCl → ZnCl₂ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["ZnO","H2SO4"], products: ["ZnSO4"], productNames: ["Сульфат цинка"],
            equation: "ZnO + H₂SO₄ → ZnSO₄ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["Na2O","HCl"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "Na₂O + 2HCl → 2NaCl + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["Na2O","H2SO4"], products: ["Na2SO4"], productNames: ["Сульфат натрия"],
            equation: "Na₂O + H₂SO₄ → Na₂SO₄ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["BaO","H2SO4"], products: ["BaSO4"], productNames: ["Сульфат бария"],
            equation: "BaO + H₂SO₄ → BaSO₄↓ + H₂O", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["PbO","HNO3"], products: ["Pb(NO3)2"], productNames: ["Нитрат свинца"],
            equation: "PbO + 2HNO₃ → Pb(NO₃)₂ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),

        // ============================================================
        // 14. КИСЛОТНЫЙ ОКСИД + ЩЁЛОЧЬ
        // ============================================================
        ChemicalReaction(reagents: ["CO2","NaOH"], products: ["Na2CO3"], productNames: ["Карбонат натрия"],
            equation: "CO₂ + 2NaOH → Na₂CO₃ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["CO2","KOH"], products: ["K2CO3"], productNames: ["Карбонат калия"],
            equation: "CO₂ + 2KOH → K₂CO₃ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["CO2","Ca(OH)2"], products: ["CaCO3"], productNames: ["Карбонат кальция"],
            equation: "CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["SO2","NaOH"], products: ["Na2SO3"], productNames: ["Сульфит натрия"],
            equation: "SO₂ + 2NaOH → Na₂SO₃ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["SO3","NaOH"], products: ["Na2SO4"], productNames: ["Сульфат натрия"],
            equation: "SO₃ + 2NaOH → Na₂SO₄ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["P2O5","NaOH"], products: ["Na3PO4"], productNames: ["Фосфат натрия"],
            equation: "P₂O₅ + 6NaOH → 2Na₃PO₄ + 3H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["SiO2","NaOH"], products: ["Na2SiO3"], productNames: ["Силикат натрия"],
            equation: "SiO₂ + 2NaOH → Na₂SiO₃ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),

        // ============================================================
        // 15. КИСЛОТА + КАРБОНАТ
        // ============================================================
        ChemicalReaction(reagents: ["Na2CO3","HCl"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂↑", effect: .gas, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["K2CO3","HCl"], products: ["KCl"], productNames: ["Хлорид калия"],
            equation: "K₂CO₃ + 2HCl → 2KCl + H₂O + CO₂↑", effect: .gas, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["CaCO3","HCl"], products: ["CaCl2"], productNames: ["Хлорид кальция"],
            equation: "CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂↑", effect: .gas, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["CaCO3","H2SO4"], products: ["CaSO4"], productNames: ["Сульфат кальция"],
            equation: "CaCO₃ + H₂SO₄ → CaSO₄ + H₂O + CO₂↑", effect: .gas, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["BaCO3","HCl"], products: ["BaCl2"], productNames: ["Хлорид бария"],
            equation: "BaCO₃ + 2HCl → BaCl₂ + H₂O + CO₂↑", effect: .gas, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["MgCO3","HCl"], products: ["MgCl2"], productNames: ["Хлорид магния"],
            equation: "MgCO₃ + 2HCl → MgCl₂ + H₂O + CO₂↑", effect: .gas, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["NaHCO3","HCl"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "NaHCO₃ + HCl → NaCl + H₂O + CO₂↑", effect: .gas, effectColorHex: "#F1F5F9"),

        // ============================================================
        // 16. КИСЛОТА + СУЛЬФИД
        // ============================================================
        ChemicalReaction(reagents: ["Na2S","HCl"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "Na₂S + 2HCl → 2NaCl + H₂S↑", effect: .gas, effectColorHex: "#FACC15",
            warning: "⚠️ H₂S очень токсичен!"),
        ChemicalReaction(reagents: ["K2S","HCl"], products: ["KCl"], productNames: ["Хлорид калия"],
            equation: "K₂S + 2HCl → 2KCl + H₂S↑", effect: .gas, effectColorHex: "#FACC15"),
        ChemicalReaction(reagents: ["FeS","HCl"], products: ["FeCl2"], productNames: ["Хлорид железа(II)"],
            equation: "FeS + 2HCl → FeCl₂ + H₂S↑", effect: .gas, effectColorHex: "#FACC15",
            warning: "⚠️ Выделяется токсичный сероводород!"),
        ChemicalReaction(reagents: ["ZnS","HCl"], products: ["ZnCl2"], productNames: ["Хлорид цинка"],
            equation: "ZnS + 2HCl → ZnCl₂ + H₂S↑", effect: .gas, effectColorHex: "#FACC15"),

        // ============================================================
        // 17. КИСЛОТА + СОЛЬ
        // ============================================================
        ChemicalReaction(reagents: ["Na2SiO3","HCl"], products: ["H2SiO3"], productNames: ["Кремниевая кислота"],
            equation: "Na₂SiO₃ + 2HCl → H₂SiO₃↓ + 2NaCl", effect: .precipitateWhite, effectColorHex: "#E5E7EB"),
        ChemicalReaction(reagents: ["Na3PO4","HCl"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "Na₃PO₄ + 3HCl → 3NaCl + H₃PO₄", effect: .glow, effectColorHex: "#FEF3C7"),

        // ============================================================
        // 18. ОСАДКИ
        // ============================================================
        ChemicalReaction(reagents: ["CuSO4","NaOH"], products: ["Cu(OH)2"], productNames: ["Гидроксид меди(II)"],
            equation: "CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄", effect: .precipitateBlue, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["CuSO4","KOH"], products: ["Cu(OH)2"], productNames: ["Гидроксид меди(II)"],
            equation: "CuSO₄ + 2KOH → Cu(OH)₂↓ + K₂SO₄", effect: .precipitateBlue, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["CuCl2","NaOH"], products: ["Cu(OH)2"], productNames: ["Гидроксид меди(II)"],
            equation: "CuCl₂ + 2NaOH → Cu(OH)₂↓ + 2NaCl", effect: .precipitateBlue, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["Cu(NO3)2","NaOH"], products: ["Cu(OH)2"], productNames: ["Гидроксид меди(II)"],
            equation: "Cu(NO₃)₂ + 2NaOH → Cu(OH)₂↓ + 2NaNO₃", effect: .precipitateBlue, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["FeCl3","NaOH"], products: ["Fe(OH)3"], productNames: ["Гидроксид железа(III)"],
            equation: "FeCl₃ + 3NaOH → Fe(OH)₃↓ + 3NaCl", effect: .precipitateBrown, effectColorHex: "#92400E"),
        ChemicalReaction(reagents: ["FeCl3","KOH"], products: ["Fe(OH)3"], productNames: ["Гидроксид железа(III)"],
            equation: "FeCl₃ + 3KOH → Fe(OH)₃↓ + 3KCl", effect: .precipitateBrown, effectColorHex: "#92400E"),
        ChemicalReaction(reagents: ["FeCl2","NaOH"], products: ["Fe(OH)2"], productNames: ["Гидроксид железа(II)"],
            equation: "FeCl₂ + 2NaOH → Fe(OH)₂↓ + 2NaCl", effect: .precipitateBrown, effectColorHex: "#365314"),
        ChemicalReaction(reagents: ["AgNO3","NaCl"], products: ["AgCl"], productNames: ["Хлорид серебра"],
            equation: "AgNO₃ + NaCl → AgCl↓ + NaNO₃", effect: .precipitateWhite, effectColorHex: "#F8FAFC"),
        ChemicalReaction(reagents: ["AgNO3","KCl"], products: ["AgCl"], productNames: ["Хлорид серебра"],
            equation: "AgNO₃ + KCl → AgCl↓ + KNO₃", effect: .precipitateWhite, effectColorHex: "#F8FAFC"),
        ChemicalReaction(reagents: ["AgNO3","CaCl2"], products: ["AgCl"], productNames: ["Хлорид серебра"],
            equation: "2AgNO₃ + CaCl₂ → 2AgCl↓ + Ca(NO₃)₂", effect: .precipitateWhite, effectColorHex: "#F8FAFC"),
        ChemicalReaction(reagents: ["AgNO3","BaCl2"], products: ["AgCl"], productNames: ["Хлорид серебра"],
            equation: "2AgNO₃ + BaCl₂ → 2AgCl↓ + Ba(NO₃)₂", effect: .precipitateWhite, effectColorHex: "#F8FAFC"),
        ChemicalReaction(reagents: ["AgNO3","HCl"], products: ["AgCl"], productNames: ["Хлорид серебра"],
            equation: "AgNO₃ + HCl → AgCl↓ + HNO₃", effect: .precipitateWhite, effectColorHex: "#F8FAFC"),
        ChemicalReaction(reagents: ["AgNO3","NaBr"], products: ["AgBr"], productNames: ["Бромид серебра"],
            equation: "AgNO₃ + NaBr → AgBr↓ + NaNO₃", effect: .precipitateYellow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["AgNO3","KBr"], products: ["AgBr"], productNames: ["Бромид серебра"],
            equation: "AgNO₃ + KBr → AgBr↓ + KNO₃", effect: .precipitateYellow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["AgNO3","NaI"], products: ["AgI"], productNames: ["Иодид серебра"],
            equation: "AgNO₃ + NaI → AgI↓ + NaNO₃", effect: .precipitateYellow, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["AgNO3","KI"], products: ["AgI"], productNames: ["Иодид серебра"],
            equation: "AgNO₃ + KI → AgI↓ + KNO₃", effect: .precipitateYellow, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["AgNO3","NaF"], products: ["AgF"], productNames: ["Фторид серебра"],
            equation: "AgNO₃ + NaF → AgF + NaNO₃", effect: .colorChange, effectColorHex: "#BBF7D0"),
        ChemicalReaction(reagents: ["BaCl2","Na2SO4"], products: ["BaSO4"], productNames: ["Сульфат бария"],
            equation: "BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["BaCl2","K2SO4"], products: ["BaSO4"], productNames: ["Сульфат бария"],
            equation: "BaCl₂ + K₂SO₄ → BaSO₄↓ + 2KCl", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["BaCl2","H2SO4"], products: ["BaSO4"], productNames: ["Сульфат бария"],
            equation: "BaCl₂ + H₂SO₄ → BaSO₄↓ + 2HCl", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["BaCl2","CuSO4"], products: ["BaSO4"], productNames: ["Сульфат бария"],
            equation: "BaCl₂ + CuSO₄ → BaSO₄↓ + CuCl₂", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["BaCl2","MgSO4"], products: ["BaSO4"], productNames: ["Сульфат бария"],
            equation: "BaCl₂ + MgSO₄ → BaSO₄↓ + MgCl₂", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["BaCl2","Na2CO3"], products: ["BaCO3"], productNames: ["Карбонат бария"],
            equation: "BaCl₂ + Na₂CO₃ → BaCO₃↓ + 2NaCl", effect: .precipitateWhite, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["CaCl2","Na2CO3"], products: ["CaCO3"], productNames: ["Карбонат кальция"],
            equation: "CaCl₂ + Na₂CO₃ → CaCO₃↓ + 2NaCl", effect: .precipitateWhite, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["CaCl2","K2CO3"], products: ["CaCO3"], productNames: ["Карбонат кальция"],
            equation: "CaCl₂ + K₂CO₃ → CaCO₃↓ + 2KCl", effect: .precipitateWhite, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["Ca(OH)2","Na2CO3"], products: ["CaCO3"], productNames: ["Карбонат кальция"],
            equation: "Ca(OH)₂ + Na₂CO₃ → CaCO₃↓ + 2NaOH", effect: .precipitateWhite, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["CuSO4","Na2S"], products: ["CuS"], productNames: ["Сульфид меди(II)"],
            equation: "CuSO₄ + Na₂S → CuS↓ + Na₂SO₄", effect: .precipitateBrown, effectColorHex: "#0F172A"),
        ChemicalReaction(reagents: ["Pb(NO3)2","Na2S"], products: ["PbS"], productNames: ["Сульфид свинца"],
            equation: "Pb(NO₃)₂ + Na₂S → PbS↓ + 2NaNO₃", effect: .precipitateBrown, effectColorHex: "#1E293B"),
        ChemicalReaction(reagents: ["ZnSO4","Na2S"], products: ["ZnS"], productNames: ["Сульфид цинка"],
            equation: "ZnSO₄ + Na₂S → ZnS↓ + Na₂SO₄", effect: .precipitateWhite, effectColorHex: "#E5E7EB"),
        ChemicalReaction(reagents: ["NiSO4","Na2S"], products: ["NiS"], productNames: ["Сульфид никеля"],
            equation: "NiSO₄ + Na₂S → NiS↓ + Na₂SO₄", effect: .precipitateBrown, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["CoCl2","Na2S"], products: ["CoS"], productNames: ["Сульфид кобальта"],
            equation: "CoCl₂ + Na₂S → CoS↓ + 2NaCl", effect: .precipitateBrown, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["MnSO4","Na2S"], products: ["MnS"], productNames: ["Сульфид марганца"],
            equation: "MnSO₄ + Na₂S → MnS↓ + Na₂SO₄", effect: .precipitateBrown, effectColorHex: "#7E22CE"),
        ChemicalReaction(reagents: ["CdCl2","Na2S"], products: ["CdS"], productNames: ["Сульфид кадмия"],
            equation: "CdCl₂ + Na₂S → CdS↓ + 2NaCl", effect: .precipitateYellow, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["HgCl2","Na2S"], products: ["HgS"], productNames: ["Сульфид ртути(II)"],
            equation: "HgCl₂ + Na₂S → HgS↓ + 2NaCl", effect: .precipitateBrown, effectColorHex: "#1C1917",
            warning: "⚠️ Соединения ртути очень токсичны!"),
        ChemicalReaction(reagents: ["Pb(NO3)2","KI"], products: ["PbI2"], productNames: ["Иодид свинца(II)"],
            equation: "Pb(NO₃)₂ + 2KI → PbI₂↓ + 2KNO₃", effect: .precipitateYellow, effectColorHex: "#FEF08A"),

        // ============================================================
        // 19. МЕТАЛЛ + СОЛЬ (ВЫТЕСНЕНИЕ)
        // ============================================================
        ChemicalReaction(reagents: ["Fe","CuSO4"], products: ["Cu"], productNames: ["Медь"],
            equation: "Fe + CuSO₄ → FeSO₄ + Cu", effect: .colorChange, effectColorHex: "#EA580C"),
        ChemicalReaction(reagents: ["Zn","CuSO4"], products: ["Cu"], productNames: ["Медь"],
            equation: "Zn + CuSO₄ → ZnSO₄ + Cu", effect: .colorChange, effectColorHex: "#EA580C"),
        ChemicalReaction(reagents: ["Mg","CuSO4"], products: ["Cu"], productNames: ["Медь"],
            equation: "Mg + CuSO₄ → MgSO₄ + Cu", effect: .colorChange, effectColorHex: "#EA580C"),
        ChemicalReaction(reagents: ["Ni","CuSO4"], products: ["NiSO4"], productNames: ["Сульфат никеля"],
            equation: "Ni + CuSO₄ → NiSO₄ + Cu", effect: .colorChange, effectColorHex: "#EA580C"),
        ChemicalReaction(reagents: ["Co","CuSO4"], products: ["CoSO4"], productNames: ["Сульфат кобальта"],
            equation: "Co + CuSO₄ → CoSO₄ + Cu", effect: .colorChange, effectColorHex: "#EA580C"),
        ChemicalReaction(reagents: ["Cd","CuSO4"], products: ["CdSO4"], productNames: ["Сульфат кадмия"],
            equation: "Cd + CuSO₄ → CdSO₄ + Cu", effect: .colorChange, effectColorHex: "#EA580C"),
        ChemicalReaction(reagents: ["Al","CuCl2"], products: ["AlCl3"], productNames: ["Хлорид алюминия"],
            equation: "2Al + 3CuCl₂ → 2AlCl₃ + 3Cu", effect: .colorChange, effectColorHex: "#DC2626"),
        ChemicalReaction(reagents: ["Fe","CuCl2"], products: ["FeCl2"], productNames: ["Хлорид железа(II)"],
            equation: "Fe + CuCl₂ → FeCl₂ + Cu", effect: .colorChange, effectColorHex: "#DC2626"),
        ChemicalReaction(reagents: ["Zn","CuCl2"], products: ["ZnCl2"], productNames: ["Хлорид цинка"],
            equation: "Zn + CuCl₂ → ZnCl₂ + Cu", effect: .colorChange, effectColorHex: "#DC2626"),
        ChemicalReaction(reagents: ["Cu","AgNO3"], products: ["Ag"], productNames: ["Серебро"],
            equation: "Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag", effect: .colorChange, effectColorHex: "#CBD5E1"),
        ChemicalReaction(reagents: ["Fe","AgNO3"], products: ["Ag"], productNames: ["Серебро"],
            equation: "Fe + 2AgNO₃ → Fe(NO₃)₂ + 2Ag", effect: .colorChange, effectColorHex: "#CBD5E1"),
        ChemicalReaction(reagents: ["Zn","AgNO3"], products: ["Ag"], productNames: ["Серебро"],
            equation: "Zn + 2AgNO₃ → Zn(NO₃)₂ + 2Ag", effect: .colorChange, effectColorHex: "#CBD5E1"),
        ChemicalReaction(reagents: ["Cu","Pb(NO3)2"], products: ["Pb"], productNames: ["Свинец"],
            equation: "Cu + Pb(NO₃)₂ → Cu(NO₃)₂ + Pb", effect: .colorChange, effectColorHex: "#64748B"),
        ChemicalReaction(reagents: ["Fe","Pb(NO3)2"], products: ["Pb"], productNames: ["Свинец"],
            equation: "Fe + Pb(NO₃)₂ → Fe(NO₃)₂ + Pb", effect: .colorChange, effectColorHex: "#64748B"),
        ChemicalReaction(reagents: ["Zn","Pb(NO3)2"], products: ["Pb"], productNames: ["Свинец"],
            equation: "Zn + Pb(NO₃)₂ → Zn(NO₃)₂ + Pb", effect: .colorChange, effectColorHex: "#64748B"),
        ChemicalReaction(reagents: ["Mg","FeSO4"], products: ["MgSO4"], productNames: ["Сульфат магния"],
            equation: "Mg + FeSO₄ → MgSO₄ + Fe", effect: .colorChange, effectColorHex: "#B45309"),
        ChemicalReaction(reagents: ["Zn","FeSO4"], products: ["ZnSO4"], productNames: ["Сульфат цинка"],
            equation: "Zn + FeSO₄ → ZnSO₄ + Fe", effect: .colorChange, effectColorHex: "#B45309"),

        // ============================================================
        // 20. ГАЛОГЕН-ОБМЕННЫЕ
        // ============================================================
        ChemicalReaction(reagents: ["Cl","NaBr"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "Cl₂ + 2NaBr → 2NaCl + Br₂", effect: .colorChange, effectColorHex: "#B91C1C"),
        ChemicalReaction(reagents: ["Cl","KI"], products: ["KCl"], productNames: ["Хлорид калия"],
            equation: "Cl₂ + 2KI → 2KCl + I₂", effect: .colorChange, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Cl","NaI"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "Cl₂ + 2NaI → 2NaCl + I₂", effect: .colorChange, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Br","KI"], products: ["KBr"], productNames: ["Бромид калия"],
            equation: "Br₂ + 2KI → 2KBr + I₂", effect: .colorChange, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Br","NaI"], products: ["NaBr"], productNames: ["Бромид натрия"],
            equation: "Br₂ + 2NaI → 2NaBr + I₂", effect: .colorChange, effectColorHex: "#7C3AED"),

        // ============================================================
        // 21. ГИДРИДЫ / КАРБИДЫ / НИТРИДЫ / ФОСФИДЫ + ВОДА
        // ============================================================
        ChemicalReaction(reagents: ["NaH","H2O"], products: ["NaOH"], productNames: ["Гидроксид натрия"],
            equation: "NaH + H₂O → NaOH + H₂↑", effect: .gas, effectColorHex: "#E0F2FE",
            warning: "⚠️ Бурное выделение водорода!"),
        ChemicalReaction(reagents: ["LiH","H2O"], products: ["LiOH"], productNames: ["Гидроксид лития"],
            equation: "LiH + H₂O → LiOH + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["CaH2","H2O"], products: ["Ca(OH)2"], productNames: ["Гидроксид кальция"],
            equation: "CaH₂ + 2H₂O → Ca(OH)₂ + 2H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["CaC2","H2O"], products: ["Ca(OH)2"], productNames: ["Гидроксид кальция"],
            equation: "CaC₂ + 2H₂O → Ca(OH)₂ + C₂H₂↑", effect: .gas, effectColorHex: "#4D7C0F",
            warning: "⚠️ Выделяется горючий ацетилен!"),
        ChemicalReaction(reagents: ["Al4C3","H2O"], products: ["Al(OH)3"], productNames: ["Гидроксид алюминия"],
            equation: "Al₄C₃ + 12H₂O → 4Al(OH)₃ + 3CH₄↑", effect: .gas, effectColorHex: "#84CC16"),
        ChemicalReaction(reagents: ["Li3N","H2O"], products: ["LiOH"], productNames: ["Гидроксид лития"],
            equation: "Li₃N + 3H₂O → 3LiOH + NH₃↑", effect: .gas, effectColorHex: "#A5B4FC"),
        ChemicalReaction(reagents: ["Mg3N2","H2O"], products: ["Mg(OH)2"], productNames: ["Гидроксид магния"],
            equation: "Mg₃N₂ + 6H₂O → 3Mg(OH)₂ + 2NH₃↑", effect: .gas, effectColorHex: "#A5B4FC"),
        ChemicalReaction(reagents: ["Ca3N2","H2O"], products: ["Ca(OH)2"], productNames: ["Гидроксид кальция"],
            equation: "Ca₃N₂ + 6H₂O → 3Ca(OH)₂ + 2NH₃↑", effect: .gas, effectColorHex: "#A5B4FC"),
        ChemicalReaction(reagents: ["Ca3P2","H2O"], products: ["Ca(OH)2"], productNames: ["Гидроксид кальция"],
            equation: "Ca₃P₂ + 6H₂O → 3Ca(OH)₂ + 2PH₃↑", effect: .gas, effectColorHex: "#F97316",
            warning: "⚠️ Фосфин PH₃ самовоспламеняется на воздухе!"),
        ChemicalReaction(reagents: ["Mg2Si","HCl"], products: ["MgCl2"], productNames: ["Хлорид магния"],
            equation: "Mg₂Si + 4HCl → 2MgCl₂ + SiH₄↑", effect: .gas, effectColorHex: "#FF6B6B"),

        // ============================================================
        // 22. ВОССТАНОВЛЕНИЕ ОКСИДОВ
        // ============================================================
        ChemicalReaction(reagents: ["CuO","H"], products: ["Cu"], productNames: ["
