import SwiftUI

enum ExamData {

    static let allTasks: [ExamTask] = [
        ExamTask(number: 1, type: .multipleChoice,
            question: "Выберите два высказывания, в которых говорится об алюминии как о простом веществе.",
            options: ["1) В качестве конструкционного материала обычно используют сплавы на его основе.",
                      "2) Соли, в которых алюминий входит в состав кислотного остатка, называются алюминаты.",
                      "3) ПДК алюминия в воде составляет 0,2 мг/л.",
                      "4) Алюминий способен накапливаться в тканях костей, мозга и печени.",
                      "5) Лидерами по производству алюминия являются Китай и Россия."],
            correctAnswer: "15",
            explanation: "О простом веществе говорят, когда речь идёт о физических свойствах, применении, производстве. Высказывания 1 и 5 — об алюминии как металле. 2, 3, 4 — о химическом элементе.",
            topic: "Атомы и молекулы"),
        ExamTask(number: 2, type: .shortAnswer,
            question: "В атоме химического элемента содержится 15 электронов. Сколько из них находятся на внешнем энергетическом уровне?",
            options: nil, correctAnswer: "5",
            explanation: "15 электронов — фосфор (P). Распределение: 2, 8, 5. На внешнем уровне — 5 электронов.",
            topic: "Строение атома"),
        ExamTask(number: 3, type: .shortAnswer,
            question: "Расположите элементы 1) фосфор 2) кремний 3) хлор в порядке увеличения атомного радиуса.",
            options: nil, correctAnswer: "312",
            explanation: "В периоде слева направо радиус уменьшается. Si → P → Cl. В порядке увеличения: Cl (3), P (1), Si (2) → 312.",
            topic: "Периодический закон"),
        ExamTask(number: 4, type: .matching,
            question: "Установите соответствие между формулой вещества и степенью окисления серы:\nA) Fe₂(SO₄)₃  B) P₂S₃  C) MgSO₃",
            options: ["1) -2", "2) +3", "3) +4", "4) +6"],
            correctAnswer: "421",
            explanation: "A) Fe₂(SO₄)₃ — сульфат, S⁺⁶ (4). B) P₂S₃ — сульфид, S⁻² (1). C) MgSO₃ — сульфит, S⁺⁴ (3).",
            topic: "Степень окисления"),
        ExamTask(number: 5, type: .multipleChoice,
            question: "Из перечня выберите два вещества с ионной связью.\n1) Li₂O  2) Al  3) NH₄I  4) HNO₃  5) SO₂",
            options: nil, correctAnswer: "13",
            explanation: "Ионная связь — между металлом и неметаллом. Li₂O и NH₄I — ионные.",
            topic: "Химическая связь"),
        ExamTask(number: 6, type: .multipleChoice,
            question: "Какие два утверждения верны для характеристики как кальция, так и калия?\n1) Во внешнем слое атом содержит один электрон.\n2) Атомный радиус больше атомного радиуса магния.\n3) Металлические свойства менее выражены, чем у магния.\n4) Соответствующий гидроксид является сильным основанием.\n5) Высший оксид имеет состав Э₂O.",
            options: nil, correctAnswer: "14",
            explanation: "Ca и K — металлы 4 периода. Правильные: 1 (у K) и 4 (оба гидроксида — сильные основания).",
            topic: "Свойства металлов"),
        ExamTask(number: 7, type: .singleChoice,
            question: "Кислотным оксидом и щёлочью соответственно являются:",
            options: ["1) SiO₂ и Ba(OH)₂", "2) NO₃ и Fe(OH)₃", "3) CaO и Cu(OH)₂", "4) CO₂ и Al(OH)₃"],
            correctAnswer: "1",
            explanation: "SiO₂ — кислотный оксид. Ba(OH)₂ — щёлочь (растворимое основание).",
            topic: "Классификация веществ"),
        ExamTask(number: 8, type: .multipleChoice,
            question: "Выберите две пары веществ, с каждым из которых реагирует оксид углерода(IV):\n1) Li₂O, NaOH  2) HCl, H₂SO₄  3) BaO, KOH  4) Ca(OH)₂, H₂O  5) Na₂O, SO₂",
            options: nil, correctAnswer: "13",
            explanation: "CO₂ — кислотный оксид. Реагирует с основными оксидами (Li₂O, BaO) и щелочами (NaOH, KOH).",
            topic: "Свойства оксидов"),
        ExamTask(number: 9, type: .matching,
            question: "Установите соответствие между реагирующими веществами и продуктами:\nA) Zn + HNO₃(конц.)  B) Zn + HNO₃(разб.)  C) Zn(NO₃)₂ →",
            options: ["1) Zn(NO₃)₂ + NO₂ + H₂O", "2) Zn(NO₃)₂ + NO + H₂O", "3) ZnO + NO₂ + O₂", "4) Zn(NO₃)₂ + H₂"],
            correctAnswer: "123",
            explanation: "A) Конц. → NO₂ (1). B) Разб. → NO (2). C) Разложение нитрата → ZnO + NO₂ + O₂ (3).",
            topic: "Химические свойства солей"),
        ExamTask(number: 10, type: .singleChoice,
            question: "К сильным электролитам относится каждое из двух веществ:",
            options: ["1) Al(OH)₃ и KOH", "2) NaOH и Ba(OH)₂", "3) Fe(OH)₃ и Fe(OH)₂", "4) Cu(OH)₂ и NaOH"],
            correctAnswer: "2",
            explanation: "NaOH и Ba(OH)₂ — щёлочи, диссоциируют полностью.",
            topic: "Электролитическая диссоциация"),
        ExamTask(number: 11, type: .singleChoice,
            question: "Признаком химической реакции не является:",
            options: ["1) выделение теплоты", "2) изменение окраски", "3) образование осадка", "4) изменение объёма"],
            correctAnswer: "4",
            explanation: "Изменение объёма — физическое явление.",
            topic: "Признаки реакций"),
        ExamTask(number: 12, type: .singleChoice,
            question: "С выделением осадка протекает реакция между:",
            options: ["1) NaI и AgNO₃", "2) MgCO₃ и HCl", "3) CaO и H₂O", "4) NaOH и Al₂O₃"],
            correctAnswer: "1",
            explanation: "NaI + AgNO₃ → AgI↓ (жёлтый осадок) + NaNO₃.",
            topic: "Реакции ионного обмена"),
        ExamTask(number: 13, type: .multipleChoice,
            question: "Выберите две пары, каждое вещество из которых при диссоциации образует сульфат-анион:\n1) Cu₂S и K₂SO₄  2) H₂SO₄ и CuSO₄  3) BaSO₄ и K₂SO₃  4) Na₂S и Na₂SO₄  5) H₂SO₄ и ZnSO₄",
            options: nil, correctAnswer: "25",
            explanation: "Сульфат-анион SO₄²⁻ из сульфатов и серной кислоты. Пары 2 и 5.",
            topic: "Электролитическая диссоциация"),
        ExamTask(number: 14, type: .singleChoice,
            question: "К сильным электролитам относится:",
            options: ["1) H₂S", "2) H₂CO₃", "3) HNO₃", "4) H₂SiO₃"],
            correctAnswer: "3",
            explanation: "HNO₃ — сильная кислота, диссоциирует полностью.",
            topic: "Электролиты"),
        ExamTask(number: 15, type: .equationInput,
            question: "Напишите уравнение реакции между железом и хлором. Укажите сумму коэффициентов.",
            options: nil, correctAnswer: "7",
            explanation: "2Fe + 3Cl₂ → 2FeCl₃. Сумма коэффициентов: 2+3+2 = 7.",
            topic: "Химические уравнения"),
        ExamTask(number: 16, type: .equationInput,
            question: "Напишите уравнение реакции между натрием и водой. Укажите сумму коэффициентов.",
            options: nil, correctAnswer: "7",
            explanation: "2Na + 2H₂O → 2NaOH + H₂↑. Сумма: 2+2+2+1 = 7.",
            topic: "Химические уравнения"),
        ExamTask(number: 17, type: .equationInput,
            question: "Напишите уравнение реакции между оксидом кальция и водой. Укажите сумму коэффициентов.",
            options: nil, correctAnswer: "3",
            explanation: "CaO + H₂O → Ca(OH)₂. Сумма: 1+1+1 = 3.",
            topic: "Химические уравнения"),
        ExamTask(number: 18, type: .shortAnswer,
            question: "Вычислите массу 0,5 моль газообразного водорода H₂. Ответ в граммах.",
            options: nil, correctAnswer: "1",
            explanation: "M(H₂) = 2 г/моль. m = n·M = 0,5·2 = 1 г.",
            topic: "Количественные отношения"),
        ExamTask(number: 19, type: .shortAnswer,
            question: "Какой объём (н.у.) займут 2 моль кислорода O₂? Ответ в литрах.",
            options: nil, correctAnswer: "44.8",
            explanation: "V = n·Vm = 2·22,4 = 44,8 л.",
            topic: "Количественные отношения"),
        ExamTask(number: 20, type: .shortAnswer,
            question: "Какова масса 3 моль воды H₂O? Ответ в граммах.",
            options: nil, correctAnswer: "54",
            explanation: "M(H₂O) = 18 г/моль. m = 3·18 = 54 г.",
            topic: "Количественные отношения"),
    ]

    static func generateVariant(count: Int = 10) -> ExamVariant {
        let shuffled = allTasks.shuffled().prefix(count)
        return ExamVariant(
            id: UUID(),
            title: "Тренировочный вариант ОГЭ",
            tasks: Array(shuffled)
        )
    }
}
