import SwiftUI

extension ChemistryData {

    static let extraReactions: [ChemicalReaction] = [

        // ==================== БОР ====================
        ChemicalReaction(reagents: ["B","F"], products: ["BF3"], productNames: ["Трифторид бора"],
            equation: "2B + 3F₂ → 2BF₃", effect: .flash, effectColorHex: "#22C55E",
            warning: "⚠️ Фтор очень активен! Реакция идёт со вспышкой, работать под тягой."),
        ChemicalReaction(reagents: ["B","Cl"], products: ["BCl3"], productNames: ["Трихлорид бора"],
            equation: "2B + 3Cl₂ → 2BCl₃", effect: .glow, effectColorHex: "#4ADE80"),
        ChemicalReaction(reagents: ["B","Br"], products: ["BBr3"], productNames: ["Трибромид бора"],
            equation: "2B + 3Br₂ → 2BBr₃", effect: .glow, effectColorHex: "#B91C1C"),
        ChemicalReaction(reagents: ["B","I"], products: ["BI3"], productNames: ["Трииодид бора"],
            equation: "2B + 3I₂ → 2BI₃", effect: .glow, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["B","O"], products: ["B2O3"], productNames: ["Оксид бора"],
            equation: "4B + 3O₂ → 2B₂O₃", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["B","N"], products: ["BN"], productNames: ["Нитрид бора"],
            equation: "2B + N₂ → 2BN (t°)", effect: .glow, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["B","H"], products: ["B2H6"], productNames: ["Дибoран"],
            equation: "2B + 3H₂ → B₂H₆ (t°, кат.)", effect: .gas, effectColorHex: "#FF6B6B"),
        ChemicalReaction(reagents: ["B","C"], products: ["B4C"], productNames: ["Карбид бора"],
            equation: "4B + C → B₄C (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["B","S"], products: ["B2S3"], productNames: ["Сульфид бора"],
            equation: "2B + 3S → B₂S₃ (t°)", effect: .glow, effectColorHex: "#FACC15"),

        // ==================== КРЕМНИЙ ====================
        ChemicalReaction(reagents: ["Si","F"], products: ["SiF4"], productNames: ["Тетрафторид кремния"],
            equation: "Si + 2F₂ → SiF₄", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Si","Cl"], products: ["SiCl4"], productNames: ["Тетрахлорид кремния"],
            equation: "Si + 2Cl₂ → SiCl₄", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Si","Br"], products: ["SiBr4"], productNames: ["Тетрабромид кремния"],
            equation: "Si + 2Br₂ → SiBr₄", effect: .glow, effectColorHex: "#B91C1C"),
        ChemicalReaction(reagents: ["Si","I"], products: ["SiI4"], productNames: ["Тетраиодид кремния"],
            equation: "Si + 2I₂ → SiI₄", effect: .glow, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Si","N"], products: ["Si3N4"], productNames: ["Нитрид кремния"],
            equation: "3Si + 2N₂ → Si₃N₄ (t°)", effect: .glow, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["Si","H"], products: ["SiH4"], productNames: ["Силан"],
            equation: "Si + 2H₂ → SiH₄ (t°, кат.)", effect: .gas, effectColorHex: "#FF6B6B",
            warning: "⚠️ Силан самовоспламеняется на воздухе!"),
        ChemicalReaction(reagents: ["Si","C"], products: ["SiC"], productNames: ["Карбид кремния"],
            equation: "Si + C → SiC (t°)", effect: .glow, effectColorHex: "#525252"),
        ChemicalReaction(reagents: ["Si","S"], products: ["SiS2"], productNames: ["Сульфид кремния"],
            equation: "Si + 2S → SiS₂ (t°)", effect: .glow, effectColorHex: "#FACC15"),
        ChemicalReaction(reagents: ["Si","Mg"], products: ["Mg2Si"], productNames: ["Силицид магния"],
            equation: "2Mg + Si → Mg₂Si (t°)", effect: .glow, effectColorHex: "#FEF08A"),

        // ==================== ТИТАН / ВАНАДИЙ ====================
        ChemicalReaction(reagents: ["Ti","O"], products: ["TiO2"], productNames: ["Оксид титана(IV)"],
            equation: "Ti + O₂ → TiO₂ (t°)", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Ti","Cl"], products: ["TiCl4"], productNames: ["Тетрахлорид титана"],
            equation: "Ti + 2Cl₂ → TiCl₄", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Ti","N"], products: ["TiN"], productNames: ["Нитрид титана"],
            equation: "2Ti + N₂ → 2TiN (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Ti","C"], products: ["TiC"], productNames: ["Карбид титана"],
            equation: "Ti + C → TiC (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["V","O"], products: ["V2O5"], productNames: ["Оксид ванадия(V)"],
            equation: "4V + 5O₂ → 2V₂O₅", effect: .flash, effectColorHex: "#F97316"),
        ChemicalReaction(reagents: ["V","Cl"], products: ["VCl5"], productNames: ["Хлорид ванадия(V)"],
            equation: "2V + 5Cl₂ → 2VCl₅", effect: .flash, effectColorHex: "#FEF08A"),

        // ==================== ХРОМ ====================
        ChemicalReaction(reagents: ["Cr","O"], products: ["Cr2O3"], productNames: ["Оксид хрома(III)"],
            equation: "4Cr + 3O₂ → 2Cr₂O₃", effect: .flash, effectColorHex: "#065F46"),
        ChemicalReaction(reagents: ["Cr","Cl"], products: ["CrCl3"], productNames: ["Хлорид хрома(III)"],
            equation: "2Cr + 3Cl₂ → 2CrCl₃", effect: .flash, effectColorHex: "#065F46"),
        ChemicalReaction(reagents: ["Cr","S"], products: ["Cr2S3"], productNames: ["Сульфид хрома(III)"],
            equation: "2Cr + 3S → Cr₂S₃ (t°)", effect: .glow, effectColorHex: "#065F46"),
        ChemicalReaction(reagents: ["Cr","N"], products: ["CrN"], productNames: ["Нитрид хрома"],
            equation: "2Cr + N₂ → 2CrN (t°)", effect: .glow, effectColorHex: "#1F2937"),

        // ==================== МАРГАНЕЦ ====================
        ChemicalReaction(reagents: ["Mn","Cl"], products: ["MnCl2"], productNames: ["Хлорид марганца(II)"],
            equation: "Mn + Cl₂ → MnCl₂", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Mn","S"], products: ["MnS"], productNames: ["Сульфид марганца(II)"],
            equation: "Mn + S → MnS (t°)", effect: .glow, effectColorHex: "#7E22CE"),
        ChemicalReaction(reagents: ["Mn","N"], products: ["Mn3N2"], productNames: ["Нитрид марганца"],
            equation: "3Mn + N₂ → Mn₃N₂ (t°)", effect: .glow, effectColorHex: "#1F2937"),

        // ==================== КОБАЛЬТ / НИКЕЛЬ ====================
        ChemicalReaction(reagents: ["Co","O"], products: ["CoO"], productNames: ["Оксид кобальта(II)"],
            equation: "2Co + O₂ → 2CoO (t°)", effect: .glow, effectColorHex: "#1D4ED8"),
        ChemicalReaction(reagents: ["Co","Cl"], products: ["CoCl2"], productNames: ["Хлорид кобальта(II)"],
            equation: "Co + Cl₂ → CoCl₂", effect: .glow, effectColorHex: "#1D4ED8"),
        ChemicalReaction(reagents: ["Co","S"], products: ["CoS"], productNames: ["Сульфид кобальта(II)"],
            equation: "Co + S → CoS (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Co","F"], products: ["CoF2"], productNames: ["Фторид кобальта(II)"],
            equation: "Co + F₂ → CoF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Ni","O"], products: ["NiO"], productNames: ["Оксид никеля(II)"],
            equation: "2Ni + O₂ → 2NiO (t°)", effect: .glow, effectColorHex: "#65A30D"),
        ChemicalReaction(reagents: ["Ni","Cl"], products: ["NiCl2"], productNames: ["Хлорид никеля(II)"],
            equation: "Ni + Cl₂ → NiCl₂", effect: .glow, effectColorHex: "#65A30D"),
        ChemicalReaction(reagents: ["Ni","S"], products: ["NiS"], productNames: ["Сульфид никеля(II)"],
            equation: "Ni + S → NiS (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Ni","F"], products: ["NiF2"], productNames: ["Фторид никеля(II)"],
            equation: "Ni + F₂ → NiF₂", effect: .flash, effectColorHex: "#22C55E"),

        // ==================== ЦИНК ====================
        ChemicalReaction(reagents: ["Zn","F"], products: ["ZnF2"], productNames: ["Фторид цинка"],
            equation: "Zn + F₂ → ZnF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Zn","Br"], products: ["ZnBr2"], productNames: ["Бромид цинка"],
            equation: "Zn + Br₂ → ZnBr₂", effect: .glow, effectColorHex: "#B91C1C"),
        ChemicalReaction(reagents: ["Zn","I"], products: ["ZnI2"], productNames: ["Иодид цинка"],
            equation: "Zn + I₂ → ZnI₂", effect: .glow, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Zn","N"], products: ["Zn3N2"], productNames: ["Нитрид цинка"],
            equation: "3Zn + N₂ → Zn₃N₂ (t°)", effect: .glow, effectColorHex: "#1F2937"),

        // ==================== ГАЛЛИЙ / ГЕРМАНИЙ ====================
        ChemicalReaction(reagents: ["Ga","Cl"], products: ["GaCl3"], productNames: ["Хлорид галлия(III)"],
            equation: "2Ga + 3Cl₂ → 2GaCl₃", effect: .glow, effectColorHex: "#64748B"),
        ChemicalReaction(reagents: ["Ga","O"], products: ["Ga2O3"], productNames: ["Оксид галлия(III)"],
            equation: "4Ga + 3O₂ → 2Ga₂O₃", effect: .glow, effectColorHex: "#64748B"),
        ChemicalReaction(reagents: ["Ge","Cl"], products: ["GeCl4"], productNames: ["Тетрахлорид германия"],
            equation: "Ge + 2Cl₂ → GeCl₄", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Ge","O"], products: ["GeO2"], productNames: ["Оксид германия(IV)"],
            equation: "Ge + O₂ → GeO₂", effect: .glow, effectColorHex: "#525252"),

        // ==================== МЫШЬЯК ====================
        ChemicalReaction(reagents: ["As","H"], products: ["AsH3"], productNames: ["Арсин"],
            equation: "2As + 3H₂ ⇄ 2AsH₃ (кат.)", effect: .gas, effectColorHex: "#7C3AED",
            warning: "🚨 Арсин AsH₃ — крайне токсичный газ!"),
        ChemicalReaction(reagents: ["As","Cl"], products: ["AsCl3"], productNames: ["Хлорид мышьяка(III)"],
            equation: "2As + 3Cl₂ → 2AsCl₃", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["As","O"], products: ["As2O3"], productNames: ["Оксид мышьяка(III)"],
            equation: "4As + 3O₂ → 2As₂O₃", effect: .glow, effectColorHex: "#7C3AED",
            warning: "🚨 As₂O₃ — сильный яд!"),
        ChemicalReaction(reagents: ["As","S"], products: ["As2S3"], productNames: ["Сульфид мышьяка(III)"],
            equation: "2As + 3S → As₂S₃", effect: .glow, effectColorHex: "#FACC15"),

        // ==================== СЕЛЕН / ТЕЛЛУР ====================
        ChemicalReaction(reagents: ["Se","O"], products: ["SeO2"], productNames: ["Оксид селена(IV)"],
            equation: "Se + O₂ → SeO₂", effect: .glow, effectColorHex: "#CA8A04"),
        ChemicalReaction(reagents: ["Se","H"], products: ["H2Se"], productNames: ["Селеноводород"],
            equation: "Se + H₂ ⇄ H₂Se (t°)", effect: .gas, effectColorHex: "#CA8A04",
            warning: "⚠️ H₂Se очень токсичен!"),
        ChemicalReaction(reagents: ["Te","O"], products: ["TeO2"], productNames: ["Оксид теллура(IV)"],
            equation: "Te + O₂ → TeO₂", effect: .glow, effectColorHex: "#A16207"),
        ChemicalReaction(reagents: ["Te","H"], products: ["H2Te"], productNames: ["Теллуроводород"],
            equation: "Te + H₂ ⇄ H₂Te (t°)", effect: .gas, effectColorHex: "#A16207"),

        // ==================== ОЛОВО / СУРЬМА / СВИНЕЦ / ВИСМУТ ====================
        ChemicalReaction(reagents: ["Sn","F"], products: ["SnF4"], productNames: ["Тетрафторид олова"],
            equation: "Sn + 2F₂ → SnF₄", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Sn","Cl"], products: ["SnCl4"], productNames: ["Тетрахлорид олова"],
            equation: "Sn + 2Cl₂ → SnCl₄", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Sn","S"], products: ["SnS"], productNames: ["Сульфид олова(II)"],
            equation: "Sn + S → SnS (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Sb","Cl"], products: ["SbCl3"], productNames: ["Хлорид сурьмы(III)"],
            equation: "2Sb + 3Cl₂ → 2SbCl₃", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Sb","O"], products: ["Sb2O3"], productNames: ["Оксид сурьмы(III)"],
            equation: "4Sb + 3O₂ → 2Sb₂O₃", effect: .glow, effectColorHex: "#525252"),
        ChemicalReaction(reagents: ["Sb","S"], products: ["Sb2S3"], productNames: ["Сульфид сурьмы(III)"],
            equation: "2Sb + 3S → Sb₂S₃", effect: .glow, effectColorHex: "#1E293B"),
        ChemicalReaction(reagents: ["Sb","H"], products: ["SbH3"], productNames: ["Стибин"],
            equation: "2Sb + 3H₂ ⇄ 2SbH₃ (кат.)", effect: .gas, effectColorHex: "#525252",
            warning: "🚨 Стибин SbH₃ очень токсичен!"),
        ChemicalReaction(reagents: ["Pb","Cl"], products: ["PbCl2"], productNames: ["Хлорид свинца(II)"],
            equation: "Pb + Cl₂ → PbCl₂", effect: .glow, effectColorHex: "#64748B"),
        ChemicalReaction(reagents: ["Pb","F"], products: ["PbF2"], productNames: ["Фторид свинца(II)"],
            equation: "Pb + F₂ → PbF₂", effect: .glow, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Bi","Cl"], products: ["BiCl3"], productNames: ["Хлорид висмута(III)"],
            equation: "2Bi + 3Cl₂ → 2BiCl₃", effect: .glow, effectColorHex: "#A78BFA"),
        ChemicalReaction(reagents: ["Bi","O"], products: ["Bi2O3"], productNames: ["Оксид висмута(III)"],
            equation: "4Bi + 3O₂ → 2Bi₂O₃", effect: .glow, effectColorHex: "#A78BFA"),
        ChemicalReaction(reagents: ["Bi","S"], products: ["Bi2S3"], productNames: ["Сульфид висмута(III)"],
            equation: "2Bi + 3S → Bi₂S₃", effect: .glow, effectColorHex: "#1E293B"),

        // ==================== БАРИЙ / СТРОНЦИЙ / РУБИДИЙ / ЦЕЗИЙ ====================
        ChemicalReaction(reagents: ["Ba","F"], products: ["BaF2"], productNames: ["Фторид бария"],
            equation: "Ba + F₂ → BaF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Ba","Br"], products: ["BaBr2"], productNames: ["Бромид бария"],
            equation: "Ba + Br₂ → BaBr₂", effect: .glow, effectColorHex: "#B91C1C"),
        ChemicalReaction(reagents: ["Ba","I"], products: ["BaI2"], productNames: ["Иодид бария"],
            equation: "Ba + I₂ → BaI₂", effect: .glow, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Ba","N"], products: ["Ba3N2"], productNames: ["Нитрид бария"],
            equation: "3Ba + N₂ → Ba₃N₂ (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Ba","C"], products: ["BaC2"], productNames: ["Карбид бария"],
            equation: "Ba + 2C → BaC₂ (t°)", effect: .glow, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["Ba","S"], products: ["BaS"], productNames: ["Сульфид бария"],
            equation: "Ba + S → BaS (t°)", effect: .glow, effectColorHex: "#FDE68A"),
        ChemicalReaction(reagents: ["Sr","Cl"], products: ["SrCl2"], productNames: ["Хлорид стронция"],
            equation: "Sr + Cl₂ → SrCl₂", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Sr","F"], products: ["SrF2"], productNames: ["Фторид стронция"],
            equation: "Sr + F₂ → SrF₂", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Rb","Cl"], products: ["RbCl"], productNames: ["Хлорид рубидия"],
            equation: "2Rb + Cl₂ → 2RbCl", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Cs","Cl"], products: ["CsCl"], productNames: ["Хлорид цезия"],
            equation: "2Cs + Cl₂ → 2CsCl", effect: .flash, effectColorHex: "#FEF08A"),

        // ==================== ЛИТИЙ / БЕРИЛЛИЙ ====================
        ChemicalReaction(reagents: ["Li","F"], products: ["LiF"], productNames: ["Фторид лития"],
            equation: "2Li + F₂ → 2LiF", effect: .flash, effectColorHex: "#22C55E"),
        ChemicalReaction(reagents: ["Li","Br"], products: ["LiBr"], productNames: ["Бромид лития"],
            equation: "2Li + Br₂ → 2LiBr", effect: .glow, effectColorHex: "#B91C1C"),
        ChemicalReaction(reagents: ["Li","I"], products: ["LiI"], productNames: ["Иодид лития"],
            equation: "2Li + I₂ → 2LiI", effect: .glow, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Li","S"], products: ["Li2S"], productNames: ["Сульфид лития"],
            equation: "2Li + S → Li₂S", effect: .flash, effectColorHex: "#FDE68A"),
        ChemicalReaction(reagents: ["Be","O"], products: ["BeO"], productNames: ["Оксид бериллия"],
            equation: "2Be + O₂ → 2BeO", effect: .flash, effectColorHex: "#FFFFFF",
            warning: "⚠️ Пыль бериллия и его соединений крайне токсична!"),
        ChemicalReaction(reagents: ["Be","Cl"], products: ["BeCl2"], productNames: ["Хлорид бериллия"],
            equation: "Be + Cl₂ → BeCl₂", effect: .flash, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["Be","F"], products: ["BeF2"], productNames: ["Фторид бериллия"],
            equation: "Be + F₂ → BeF₂", effect: .flash, effectColorHex: "#22C55E"),

        // ==================== ГАЛОГЕН-ОБМЕННЫЕ ====================
        ChemicalReaction(reagents: ["Cl","NaBr"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "Cl₂ + 2NaBr → 2NaCl + Br₂", effect: .colorChange, effectColorHex: "#B91C1C"),
        ChemicalReaction(reagents: ["Cl","KI"], products: ["KCl"], productNames: ["Хлорид калия"],
            equation: "Cl₂ + 2KI → 2KCl + I₂", effect: .colorChange, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Cl","NaI"], products: ["NaCl"], productNames: ["Хлорид натрия"],
            equation: "Cl₂ + 2NaI → 2NaCl + I₂", effect: .colorChange, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Br","KI"], products: ["KBr"], productNames: ["Бромид калия"],
            equation: "Br₂ + 2KI → 2KBr + I₂", effect: .colorChange, effectColorHex: "#7C3AED"),
        ChemicalReaction(reagents: ["Br","NaI"], products: ["NaBr"], productNames: ["Бромид натрия"],
            equation: "Br₂ + 2NaI → 2NaBr + I₂", effect: .colorChange, effectColorHex: "#7C3AED"),

        // ==================== ГИДРИДЫ + ВОДА ====================
        ChemicalReaction(reagents: ["NaH","H2O"], products: ["NaOH"], productNames: ["Гидроксид натрия"],
            equation: "NaH + H₂O → NaOH + H₂↑", effect: .gas, effectColorHex: "#E0F2FE",
            warning: "⚠️ Бурное выделение водорода!"),
        ChemicalReaction(reagents: ["LiH","H2O"], products: ["LiOH"], productNames: ["Гидроксид лития"],
            equation: "LiH + H₂O → LiOH + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["CaH2","H2O"], products: ["Ca(OH)2"], productNames: ["Гидроксид кальция"],
            equation: "CaH₂ + 2H₂O → Ca(OH)₂ + 2H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),

        // ==================== КАРБИДЫ + ВОДА ====================
        ChemicalReaction(reagents: ["CaC2","H2O"], products: ["Ca(OH)2"], productNames: ["Гидроксид кальция"],
            equation: "CaC₂ + 2H₂O → Ca(OH)₂ + C₂H₂↑", effect: .gas, effectColorHex: "#4D7C0F",
            warning: "⚠️ Выделяется горючий ацетилен!"),
        ChemicalReaction(reagents: ["Al4C3","H2O"], products: ["Al(OH)3"], productNames: ["Гидроксид алюминия"],
            equation: "Al₄C₃ + 12H₂O → 4Al(OH)₃ + 3CH₄↑", effect: .gas, effectColorHex: "#84CC16"),

        // ==================== НИТРИДЫ + ВОДА ====================
        ChemicalReaction(reagents: ["Li3N","H2O"], products: ["LiOH"], productNames: ["Гидроксид лития"],
            equation: "Li₃N + 3H₂O → 3LiOH + NH₃↑", effect: .gas, effectColorHex: "#A5B4FC"),
        ChemicalReaction(reagents: ["Mg3N2","H2O"], products: ["Mg(OH)2"], productNames: ["Гидроксид магния"],
            equation: "Mg₃N₂ + 6H₂O → 3Mg(OH)₂ + 2NH₃↑", effect: .gas, effectColorHex: "#A5B4FC"),
        ChemicalReaction(reagents: ["Ca3N2","H2O"], products: ["Ca(OH)2"], productNames: ["Гидроксид кальция"],
            equation: "Ca₃N₂ + 6H₂O → 3Ca(OH)₂ + 2NH₃↑", effect: .gas, effectColorHex: "#A5B4FC"),

        // ==================== ФОСФИД + ВОДА ====================
        ChemicalReaction(reagents: ["Ca3P2","H2O"], products: ["Ca(OH)2"], productNames: ["Гидроксид кальция"],
            equation: "Ca₃P₂ + 6H₂O → 3Ca(OH)₂ + 2PH₃↑", effect: .gas, effectColorHex: "#F97316",
            warning: "⚠️ Фосфин PH₃ самовоспламеняется на воздухе!"),

        // ==================== СИЛИЦИД + КИСЛОТА ====================
        ChemicalReaction(reagents: ["Mg2Si","HCl"], products: ["MgCl2"], productNames: ["Хлорид магния"],
            equation: "Mg₂Si + 4HCl → 2MgCl₂ + SiH₄↑", effect: .gas, effectColorHex: "#FF6B6B"),

        // ==================== ОКСИДЫ + ВОДА ====================
        ChemicalReaction(reagents: ["B2O3","H2O"], products: ["H3BO3"], productNames: ["Борная кислота"],
            equation: "B₂O₃ + 3H₂O → 2H₃BO₃", effect: .glow, effectColorHex: "#FEF08A"),

        // ==================== КИСЛОТНО-ОСНОВНЫЕ ====================
        ChemicalReaction(reagents: ["Ca(OH)2","H3PO4"], products: ["Ca3(PO4)2"], productNames: ["Фосфат кальция"],
            equation: "3Ca(OH)₂ + 2H₃PO₄ → Ca₃(PO₄)₂↓ + 6H₂O", effect: .precipitateWhite, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["Ba(OH)2","HNO3"], products: ["Ba(NO3)2"], productNames: ["Нитрат бария"],
            equation: "Ba(OH)₂ + 2HNO₃ → Ba(NO₃)₂ + 2H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["Ca(OH)2","HNO3"], products: ["Ca(NO3)2"], productNames: ["Нитрат кальция"],
            equation: "Ca(OH)₂ + 2HNO₃ → Ca(NO₃)₂ + 2H₂O", effect: .glow, effectColorHex: "#FEF3C7"),

        // ==================== МЕТАЛЛ + КИСЛОТА ====================
        ChemicalReaction(reagents: ["Ni","HCl"], products: ["NiCl2"], productNames: ["Хлорид никеля(II)"],
            equation: "Ni + 2HCl → NiCl₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Co","HCl"], products: ["CoCl2"], productNames: ["Хлорид кобальта(II)"],
            equation: "Co + 2HCl → CoCl₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Sn","HCl"], products: ["SnCl2"], productNames: ["Хлорид олова(II)"],
            equation: "Sn + 2HCl → SnCl₂ + H₂↑", effect: .gas, effectColorHex: "#E0F2FE"),
        ChemicalReaction(reagents: ["Ba","H2SO4"], products: ["BaSO4"], productNames: ["Сульфат бария"],
            equation: "Ba + H₂SO₄ → BaSO₄↓ + H₂↑", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
        ChemicalReaction(reagents: ["Ca","H2SO4"], products: ["CaSO4"], productNames: ["Сульфат кальция"],
            equation: "Ca + H₂SO₄ → CaSO₄↓ + H₂↑", effect: .precipitateWhite, effectColorHex: "#F1F5F9"),

        // ==================== МЕТАЛЛ + СОЛЬ ====================
        ChemicalReaction(reagents: ["Ni","CuSO4"], products: ["NiSO4"], productNames: ["Сульфат никеля"],
            equation: "Ni + CuSO₄ → NiSO₄ + Cu", effect: .colorChange, effectColorHex: "#EA580C"),
        ChemicalReaction(reagents: ["Co","CuSO4"], products: ["CoSO4"], productNames: ["Сульфат кобальта"],
            equation: "Co + CuSO₄ → CoSO₄ + Cu", effect: .colorChange, effectColorHex: "#EA580C"),
        ChemicalReaction(reagents: ["Cd","CuSO4"], products: ["CdSO4"], productNames: ["Сульфат кадмия"],
            equation: "Cd + CuSO₄ → CdSO₄ + Cu", effect: .colorChange, effectColorHex: "#EA580C"),
        ChemicalReaction(reagents: ["Mg","FeSO4"], products: ["MgSO4"], productNames: ["Сульфат магния"],
            equation: "Mg + FeSO₄ → MgSO₄ + Fe", effect: .colorChange, effectColorHex: "#B45309"),
        ChemicalReaction(reagents: ["Zn","FeSO4"], products: ["ZnSO4"], productNames: ["Сульфат цинка"],
            equation: "Zn + FeSO₄ → ZnSO₄ + Fe", effect: .colorChange, effectColorHex: "#B45309"),

        // ==================== НОВЫЕ ОСАДКИ ====================
        ChemicalReaction(reagents: ["CuSO4","KOH"], products: ["Cu(OH)2"], productNames: ["Гидроксид меди(II)"],
            equation: "CuSO₄ + 2KOH → Cu(OH)₂↓ + K₂SO₄", effect: .precipitateBlue, effectColorHex: "#3B82F6"),
        ChemicalReaction(reagents: ["FeCl3","KOH"], products: ["Fe(OH)3"], productNames: ["Гидроксид железа(III)"],
            equation: "FeCl₃ + 3KOH → Fe(OH)₃↓ + 3KCl", effect: .precipitateBrown, effectColorHex: "#92400E"),
        ChemicalReaction(reagents: ["CdCl2","Na2S"], products: ["CdS"], productNames: ["Сульфид кадмия"],
            equation: "CdCl₂ + Na₂S → CdS↓ + 2NaCl", effect: .precipitateYellow, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["HgCl2","Na2S"], products: ["HgS"], productNames: ["Сульфид ртути(II)"],
            equation: "HgCl₂ + Na₂S → HgS↓ + 2NaCl", effect: .precipitateBrown, effectColorHex: "#1C1917",
            warning: "⚠️ Соединения ртути очень токсичны!"),
        ChemicalReaction(reagents: ["NiSO4","Na2S"], products: ["NiS"], productNames: ["Сульфид никеля"],
            equation: "NiSO₄ + Na₂S → NiS↓ + Na₂SO₄", effect: .precipitateBrown, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["CoCl2","Na2S"], products: ["CoS"], productNames: ["Сульфид кобальта"],
            equation: "CoCl₂ + Na₂S → CoS↓ + 2NaCl", effect: .precipitateBrown, effectColorHex: "#1F2937"),
        ChemicalReaction(reagents: ["MnSO4","Na2S"], products: ["MnS"], productNames: ["Сульфид марганца"],
            equation: "MnSO₄ + Na₂S → MnS↓ + Na₂SO₄", effect: .precipitateBrown, effectColorHex: "#7E22CE"),

        // ==================== РАЗЛОЖЕНИЯ ====================
        ChemicalReaction(reagents: ["BaCO3","O"], products: ["BaO"], productNames: ["Оксид бария"],
            equation: "BaCO₃ →t°→ BaO + CO₂↑", effect: .gas, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["MgCO3","O"], products: ["MgO"], productNames: ["Оксид магния"],
            equation: "MgCO₃ →t°→ MgO + CO₂↑", effect: .gas, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["CuCO3","O"], products: ["CuO"], productNames: ["Оксид меди(II)"],
            equation: "CuCO₃ →t°→ CuO + CO₂↑", effect: .gas, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["Mg(OH)2","O"], products: ["MgO"], productNames: ["Оксид магния"],
            equation: "Mg(OH)₂ →t°→ MgO + H₂O", effect: .colorChange, effectColorHex: "#FCD34D"),
        ChemicalReaction(reagents: ["Zn(OH)2","O"], products: ["ZnO"], productNames: ["Оксид цинка"],
            equation: "Zn(OH)₂ →t°→ ZnO + H₂O", effect: .colorChange, effectColorHex: "#E5E7EB"),

        // ==================== ОРГАНИКА ДОП. ====================
        ChemicalReaction(reagents: ["C2H5OH","HBr"], products: ["C2H5Br"], productNames: ["Бромэтан"],
            equation: "C₂H₅OH + HBr → C₂H₅Br + H₂O", effect: .glow, effectColorHex: "#FEE2E2"),
        ChemicalReaction(reagents: ["C2H5OH","HCl"], products: ["C2H5Cl"], productNames: ["Хлорэтан"],
            equation: "C₂H₅OH + HCl → C₂H₅Cl + H₂O (кат.)", effect: .glow, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["CH3OH","HCl"], products: ["CH3Cl"], productNames: ["Хлорметан"],
            equation: "CH₃OH + HCl → CH₃Cl + H₂O (кат.)", effect: .glow, effectColorHex: "#FEF08A"),
        ChemicalReaction(reagents: ["CH4","Cl"], products: ["CH3Cl"], productNames: ["Хлорметан"],
            equation: "CH₄ + Cl₂ → CH₃Cl + HCl (свет)", effect: .explosion, effectColorHex: "#FEF08A",
            warning: "⚠️ Реакция на свету может сопровождаться взрывом!"),
        ChemicalReaction(reagents: ["C2H6","Cl"], products: ["C2H5Cl"], productNames: ["Хлорэтан"],
            equation: "C₂H₆ + Cl₂ → C₂H₅Cl + HCl (свет)", effect: .glow, effectColorHex: "#FEF08A"),

        // ==================== ВОССТАНОВЛЕНИЕ ОКСИДОВ ====================
        ChemicalReaction(reagents: ["SnO2","C"], products: ["Sn"], productNames: ["Олово"],
            equation: "SnO₂ + 2C → Sn + 2CO↑", effect: .glow, effectColorHex: "#D4D4D8"),
        ChemicalReaction(reagents: ["MnO2","C"], products: ["Mn"], productNames: ["Марганец"],
            equation: "MnO₂ + 2C → Mn + 2CO↑", effect: .glow, effectColorHex: "#7E22CE"),
        ChemicalReaction(reagents: ["Cr2O3","C"], products: ["Cr"], productNames: ["Хром"],
            equation: "Cr₂O₃ + 3C → 2Cr + 3CO↑", effect: .glow, effectColorHex: "#065F46"),

        // ==================== АЛЮМИНОТЕРМИЯ ====================
        ChemicalReaction(reagents: ["Fe2O3","Al"], products: ["Fe"], productNames: ["Железо"],
            equation: "Fe₂O₃ + 2Al → 2Fe + Al₂O₃", effect: .explosion, effectColorHex: "#F97316",
            warning: "🚨 Алюминотермия — температура до 2500°C!"),
        ChemicalReaction(reagents: ["Cr2O3","Al"], products: ["Cr"], productNames: ["Хром"],
            equation: "Cr₂O₃ + 2Al → 2Cr + Al₂O₃", effect: .explosion, effectColorHex: "#EA580C"),
        ChemicalReaction(reagents: ["MnO2","Al"], products: ["Mn"], productNames: ["Марганец"],
            equation: "3MnO₂ + 4Al → 3Mn + 2Al₂O₃", effect: .explosion, effectColorHex: "#EA580C"),

        // ==================== ОКСИДЫ С КИСЛОТАМИ ====================
        ChemicalReaction(reagents: ["CuO","HNO3"], products: ["Cu(NO3)2"], productNames: ["Нитрат меди(II)"],
            equation: "CuO + 2HNO₃ → Cu(NO₃)₂ + H₂O", effect: .colorChange, effectColorHex: "#0E7490"),
        ChemicalReaction(reagents: ["ZnO","H2SO4"], products: ["ZnSO4"], productNames: ["Сульфат цинка"],
            equation: "ZnO + H₂SO₄ → ZnSO₄ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["MgO","H2SO4"], products: ["MgSO4"], productNames: ["Сульфат магния"],
            equation: "MgO + H₂SO₄ → MgSO₄ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["CaO","H2SO4"], products: ["CaSO4"], productNames: ["Сульфат кальция"],
            equation: "CaO + H₂SO₄ → CaSO₄↓ + H₂O", effect: .precipitateWhite, effectColorHex: "#F1F5F9"),
        ChemicalReaction(reagents: ["Na2O","H2SO4"], products: ["Na2SO4"], productNames: ["Сульфат натрия"],
            equation: "Na₂O + H₂SO₄ → Na₂SO₄ + H₂O", effect: .glow, effectColorHex: "#FEF3C7"),
        ChemicalReaction(reagents: ["BaO","H2SO4"], products: ["BaSO4"], productNames: ["Сульфат бария"],
            equation: "BaO + H₂SO₄ → BaSO₄↓ + H₂O", effect: .precipitateWhite, effectColorHex: "#FFFFFF"),
    ]
}
